---
title: Mouse.release()
---

= Mouse.release()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Envia ao computador a mensagem que um botão previamente apertado e segurado (através de link:../mousepress[Mouse.press()]) foi liberado. `Mouse.release()` por padrão usa o botão esquerdo.
[%hardbreaks]


[float]
=== Sintaxe
`Mouse.release();` +
`Mouse.release(botão);`

[float]
=== Parâmetros
`botão`: qual botão do mouse liberar - char

* `MOUSE_LEFT` (padrão)

* `MOUSE_RIGHT`

* `MOUSE_MIDDLE`

Que correspondem ao botão esquerdo, direito e do meio, respectivamente.

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup() {
  // o botão que inicia o apertar do botão do mouse
  pinMode(2, INPUT);
  // o botão que libera do botão do mouse
  pinMode(3, INPUT);
  // inicia a biblioteca Mouse
  Mouse.begin();
}

void loop() {
  // se o botão conectado ao pino 2 for pressionado, aperta e segura o botão do mouse virtual
  if (digitalRead(2) == HIGH) {
    Mouse.press();
  }
  // se o botão conectado ao pino 2 for pressionado, solta o botão do mouse virtual
  if (digitalRead(3) == HIGH) {
    Mouse.release();
  }
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../mouseclick[Mouse.click()] +
#LINGUAGEM# link:../mouseend[Mouse.end()] +
#LINGUAGEM# link:../mousemove[Mouse.move()] +
#LINGUAGEM# link:../mousepress[Mouse.press()] +
#LINGUAGEM# link:../mouseispressed[Mouse.isPressed()] +

--
// SEE ALSO SECTION ENDS
