---
title: Mouse.isPressed()
---




= Mouse.isPressed()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Checks the current status of all mouse buttons, and reports if any are pressed or not.
[%hardbreaks]


[float]
=== Sintaxe
`Mouse.isPressed();` +
`Mouse.isPressed(button);`

[float]
=== Parâmetros
When there is no value passed, it checks the status of the left mouse button.

`button`: which mouse button to check - `char`

* `MOUSE_LEFT (default)`

* `MOUSE_RIGHT`

* `MOUSE_MIDDLE`

[float]
=== Retorna
`boolean` : reports whether a button is pressed or not.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup(){
  //The switch that will initiate the Mouse press
  pinMode(2,INPUT);
  //The switch that will terminate the Mouse press
  pinMode(3,INPUT);
  //Start serial communication with the computer
  Serial1.begin(9600);
  //initiate the Mouse library
  Mouse.begin();
}

void loop(){
  //a variable for checking the button's state
  int mouseState=0;
  //if the switch attached to pin 2 is closed, press and hold the left mouse button and save the state ina  variable
  if(digitalRead(2) == HIGH){
    Mouse.press();
    mouseState=Mouse.isPressed();
  }
  //if the switch attached to pin 3 is closed, release the left mouse button and save the state in a variable
  if(digitalRead(3) == HIGH){
    Mouse.release();
    mouseState=Mouse.isPressed();
  }
  //print out the current mouse button state
  Serial1.println(mouseState);
  delay(10);
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../mouseclick[Mouse.click()]
#LINGUAGEM# link:../mouseend[Mouse.end()]
#LINGUAGEM# link:../mousemove[Mouse.move()]
#LINGUAGEM# link:../mousepress[Mouse.press()]
#LINGUAGEM# link:../mouserelease[Mouse.release()]

--
// SEE ALSO SECTION ENDS
