---
title: Mouse.press()
---

= Mouse.press()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Envia o apertar de um botão do mouse ao computador conectado. Isso é equivalente a clicar e segurar o botão do mouse. O botão segurado pode ser liberado com  link:../mouserelease[Mouse.release()].

Antes de usar `Mouse.press()`, você precisa iniciar a comunicação com link:../mousebegin[Mouse.begin()].

`Mouse.press()` por padrão aperta o botão esquerdo do mouse.
[%hardbreaks]


[float]
=== Sintaxe
`Mouse.press()` +
`Mouse.press(botão)`


[float]
=== Parâmetros
`botão`: qual o botão do mouse a se apertar - `char`

* `MOUSE_LEFT (padrão)`

* `MOUSE_RIGHT`

* `MOUSE_MIDDLE`

Que correspondem ao botão esquerdo, direito e do meio, respectivamente.

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup() {
  // o botão que inicia o apertar do botão do mouse
  pinMode(2, INPUT);
  // o botão que libera do botão do mouse
  pinMode(3, INPUT);
  // inicia a biblioteca Mouse
  Mouse.begin();
}

void loop() {
  // se o botão conectado ao pino 2 for pressionado, aperta e segura o botão do mouse virtual
  if (digitalRead(2) == HIGH) {
    Mouse.press();
  }
  // se o botão conectado ao pino 2 for pressionado, solta o botão do mouse virtual
  if (digitalRead(3) == HIGH) {
    Mouse.release();
  }
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Quando você usa a função `Mouse.press()`, o Arduino toma o controle do computador! Tenha certeza que você tem controle de quando as comandos vão ser enviados antes de usar essa função. Pode ser difícil gravar um novo código no Arduino se ele estiver enviando cliques  o tempo todo. Um botão para ativar/desativar o controle do mouse emulado é bastante efetivo.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../mouseclick[Mouse.click()] +
#LINGUAGEM# link:../mouseend[Mouse.end()] +
#LINGUAGEM# link:../mousemove[Mouse.move()] +
#LINGUAGEM# link:../mouserelease[Mouse.release()] +
#LINGUAGEM# link:../mouseispressed[Mouse.isPressed()] +

--
// SEE ALSO SECTION ENDS
