---
title: Mouse.click()
---

= Mouse.click()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Envia um clique momentâneo para o computador, na localização atual do cursor. Isso equivale a pressionar e liberar imediatamente o botão do mouse.

`Mouse.click()` por padrão usa o botão esquerdo do mouse, mas os outros botões podem ser passados para a função com um argumento opcional.
[%hardbreaks]


[float]
=== Sintaxe
`Mouse.click();` +
`Mouse.click(botão);`


[float]
=== Parâmetros
`botão`: qual o botão do mouse a ser pressionado. Um dos valores abaixo. - `char`

* `MOUSE_LEFT` (padrão)
* `MOUSE_RIGHT`
* `MOUSE_MIDDLE`

Que são o botão esquerdo, direito e do meio, respectivamente.

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup(){
  pinMode(2,INPUT);
  // inicializa a biblioteca mouse
  Mouse.begin();
}

void loop(){
  //se o botão for pressionado, envia um clique com o botão esquerdo do mouse
  if(digitalRead(2) == HIGH){
    Mouse.click();
  }
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Quando você usa a função `Mouse.click()`, o Arduino toma o controle do computador! Tenha certeza que você tem controle de quando as comanndos vão ser enviados antes de usar essa função. Pode ser difícil gravar um novo código no Arduino se ele estiver enviando cliques  o tempo todo. Um botão para ativar/desativar o controle do mouse emulado é bastante efetivo.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../mouseend[Mouse.end()] +
#LINGUAGEM# link:../mousemove[Mouse.move()] +
#LINGUAGEM# link:../mousepress[Mouse.press()] +
#LINGUAGEM# link:../mouserelease[Mouse.release()] +
#LINGUAGEM# link:../mouseispressed[Mouse.isPressed()] +

--
// SEE ALSO SECTION ENDS
