---
title: Mouse.isPressed()
---

= Mouse.isPressed()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Checa o estado atual de um botão do mouse emulado e reporta se o mesmo está pressionado ou não.
[%hardbreaks]


[float]
=== Sintaxe
`Mouse.isPressed();` +
`Mouse.isPressed(botão);`

[float]
=== Parâmetros
Quando nenhum argumento é passado, a função checa o estado do botão esquerdo.

`botão`: qual botão do mouse checar - `char`

* `MOUSE_LEFT (padrão)`

* `MOUSE_RIGHT`

* `MOUSE_MIDDLE`

Os argumentos acima são o botão esquerdo, direito e do meio, respectivamente.

[float]
=== Retorna
Se o botão do mouse passado para a função está pressionado ou não - `bool`

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup() {
  // o botão que inicia o clique do mouse
  pinMode(2, INPUT);
  // o botão que termina o clique do mouse
  pinMode(3, INPUT);

  // inicia a comunicação serial com o computador
  Serial.begin(9600);

  // inicia a biblioteca Mouse
  Mouse.begin();
}

void loop() {
  // variável para checar o esatdo do botão do mouse
  int mouseState = 0;

  // se o botão conectado ao pino 2 for pressionado, aperta e segura o botão do mouse virtual e salva o estado do mesmo na variável
  if (digitalRead(2) == HIGH) {
    Mouse.press();
    mouseState = Mouse.isPressed();
  }

  // se o botão conectado ao pino 3 for pressionado, libera o botão do mouse virtual e salva o estado do mesmo na variável
  if (digitalRead(3) == HIGH) {
    Mouse.release();
    mouseState = Mouse.isPressed();
  }

  // imprime o estado atual do botão do mouse emulado
  Serial.println(mouseState);
  delay(10);
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../mouseclick[Mouse.click()] +
#LINGUAGEM# link:../mouseend[Mouse.end()] +
#LINGUAGEM# link:../mousemove[Mouse.move()] +
#LINGUAGEM# link:../mousepress[Mouse.press()] +
#LINGUAGEM# link:../mouserelease[Mouse.release()] +

--
// SEE ALSO SECTION ENDS
