---
title: Mouse.release()
---




= Mouse.release()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Sends a message that a previously pressed button (invoked through link:../mousepress[Mouse.press()]) is released. Mouse.release() defaults to the left button.
[%hardbreaks]


[float]
=== Sintaxe
`Mouse.release();` +
`Mouse.release(button);`

[float]
=== Parâmetros
`button`: which mouse button to press - char

* `MOUSE_LEFT` (default)

* `MOUSE_RIGHT`

* `MOUSE_MIDDLE`

[float]
=== Retorna
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup(){
  //The switch that will initiate the Mouse press
  pinMode(2,INPUT);
  //The switch that will terminate the Mouse press
  pinMode(3,INPUT);
  //initiate the Mouse library
  Mouse.begin();
}

void loop(){
  //if the switch attached to pin 2 is closed, press and hold the left mouse button
  if(digitalRead(2) == HIGH){
    Mouse.press();
  }
  //if the switch attached to pin 3 is closed, release the left mouse button
  if(digitalRead(3) == HIGH){
    Mouse.release();
  }
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
When you use the `Mouse.release()` command, the Arduino takes over your mouse! Make sure you have control before you use the command. A pushbutton to toggle the mouse control state is effective.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../mouseclick[Mouse.click()]
#LINGUAGEM# link:../mouseend[Mouse.end()]
#LINGUAGEM# link:../mousemove[Mouse.move()]
#LINGUAGEM# link:../mousepress[Mouse.press()]
#LINGUAGEM# link:../mouseispressed[Mouse.isPressed()]

--
// SEE ALSO SECTION ENDS
