---
title: digitalRead()
categories: [ "Funções" ]
subCategories: [ "Entradas e Saídas Digitais" ]
---

:source-highlighter: pygments
:pygments-style: arduino
//
:ext-relative: .html

= digitalRead()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Lê o valor de um pino digital especificado, que pode ser `HIGH` ou `LOW`.
[%hardbreaks]


[float]
=== Sintaxe
`digitalRead(pino)`


[float]
=== Parâmetros
`pino`: o número do pino digital que você quiser verificar
[float]
=== Retorna
`HIGH` ou `LOW`

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Aciona o pino 13 para o mesmo valor que o pino 7, declarado como entrada.

//[source,arduino]
----
int ledPin = 13;   // LED conectado ao pino digital 13
int inPin = 7;     // botão conectado ao pino digital 7
int val = 0;       // variável para guardar o valor lido

void setup()
{
  pinMode(ledPin, OUTPUT);      // configura o pino digital 13 como saída
  pinMode(inPin, INPUT);        // configura o pino digital 7 como entrada
}

void loop()
{
  val = digitalRead(inPin);     // lê o pino de entrada
  digitalWrite(ledPin, val);    // aciona o LED com o valor lido do botão
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Se o pino não está conectado a nada, digitalRead() pode retornar tanto HIGH como LOW (e isso pode mudar aleatoriamente).

Os pinos de entrada analógica podem ser também usados como pinos digitais, referidos como A0, A1, etc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="example"]
* #EXAMPLE# Tutorial: (http://arduino.cc/en/Tutorial/DigitalPins[Digital Pins])

--
// SEE ALSO SECTION ENDS
