---
title: digitalWrite()
categories: [ "Functions" ]
subCategories: [ "Entradas e Saídas Digitais" ]
---


//
:ext-relative: .html

= digitalWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Aciona um valor `HIGH` ou `LOW` em um pino digital.

Se o pino for configurado como saída (OUTPUT) com a função `pinMode()`, sua tensão será acionada para o valor correspondente: 5V (ou 3.3V em placas alimentadas com 3.3V como o DUE) para o valor `HIGH`, 0V (ou ground) para `LOW`.
[%hardbreaks]

Se o pino for configurado como entrada (INPUT), a função `digitalWrite()` irá ativar (HIGH) ou desativar (LOW) o resistor interno de pull-up no pino de entrada. É recomendado configurar pinMode() com INPUT_PULLUP para ativar o resistor interno de pull-up. Veja o tutorial sobre pinos digitais para mais informações.
[%hardbreaks]

Se você não configurar o pino com `pinMode()` e `OUTPUT`, e conectar um LED ao pino, quando chamar `digitalWrite(HIGH)`, o LED pode aparecer um pouco apagado. Sem configurar explicitamente `pinMode()`, `digitalWrite()` irá apenas ativar o resistor de pull-up interno, que age como um grande resistor limitador de corrente.
[%hardbreaks]

[float]
=== Sintaxe
`digitalWrite(pino, valor)`


[float]
=== Parâmetros
`pino`: o número do pino

`valor`: `HIGH` ou `LOW`

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The código configura o pino digital 13 como `OUTPUT` e troca seu estado entre `HIGH` e `LOW`

[source,arduino]
----
void setup()
{
  pinMode(13, OUTPUT);          // configura o pino digital 13 como saída
}

void loop()
{
  digitalWrite(13, HIGH);       // ativa o pino digital 13
  delay(1000);                  // espera por um segundo
  digitalWrite(13, LOW);        // desativa o pino digital 13
  delay(1000);                  // espera por um segundo
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Os pinos de entrada analógica podem ser também usados como pinos digitais, referidos como A0, A1, etc. As exceções são os pinos A6 e A7 do Arduino Nano, Pro Mini, e Mini; os quais podem ser usados apenas como pinos de entrada analógica.
--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
* #EXEMPLO# http://arduino.cc/en/Tutorial/DigitalPins[Tutorial: Pinos digitais (Em Inglês)]

--
// SEE ALSO SECTION ENDS
