---
title: pinMode()
categories: [ "Functions" ]
subCategories: [ "Entradas e Saídas Digitais" ]
---


//
:ext-relative: .html

= pinMode()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Configura o pino especificado para funcionar como uma entrada ou saída. Veja a descrição dos http://arduino.cc/en/Tutorial/DigitalPins[pinos digitais (em Inglês)] para mais detalhes sobre a funcionalidade dos pinos.
[%hardbreaks]
Desde a versão 1.0.1, é possível ativar os resistores internos de pull-up como o modo INPUT_PULLUP. Adicionalmente, o modo INPUT explicitamente desativa os resistores pull-up internos.
[%hardbreaks]


[float]
=== Sintaxe
`pinMode(pino, modo)`

[float]
=== Parâmetros
`pino`: the número do pino do Arduino no qual se quer configurar o modo

`modo`: o modo do pino. Este pode ser `INPUT`, `OUTPUT` ou `INPUT_PULLUP`; que correspondem respectivamente a entrada, saída e entrada com pull-up ativado.

//Check how to add links

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
The código configura o pino digital 13 como `OUTPUT` e troca seu estado entre `HIGH` e `LOW`

[source,arduino]
----
void setup() {
  pinMode(13, OUTPUT);    // configura o pino digital 13 como saída
}

void loop() {
  digitalWrite(13, HIGH); // ativa o pino digital 13
  delay(1000);            // espera por um segundo
  digitalWrite(13, LOW);  // desativa o pino digital 13
  delay(1000);            // espera por um segundo
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Os pinos de entrada analógica podem ser também usados como pinos digitais, referidos como A0, A1, etc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
* #EXEMPLO# http://arduino.cc/en/Tutorial/DigitalPins[Descrição dos pinos digitais (em inglês)^]

--
// SEE ALSO SECTION ENDS
