---
title: sizeof()
categories: [ "Variables" ]
subCategories: [ "Utilities" ]
---

= sizeof

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
O operador `sizeof` retorna o número de bytes de uma variável, ou o número de bytes ocupados em um vetor.
[%hardbreaks]


[float]
=== Sintaxe
`sizeof(variável)`


[float]
=== Parâmetros
`variável`: uma variável ou vetor de qualquer tipo (ex: int, float, byte)

[float]
=== Retorna
O número de bytes em uma variável ou o número de bytes ocupados em um vetor. (size_t)

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O perador `sizeof` é útil para manipular arrays (tais como strings), onde é conveniente ser possível mudar o tamanho do vetor sem quebrar outras partes do programa.

O programa abaixo imprime um string um caractere de cada vez. Tente mudar o texto da frase.

[source,arduino]
----
char minhaStr[] = "Esse é um teste";

void setup() {
  Serial.begin(9600);
}

void loop() {
  for (byte i = 0; i < sizeof(minhaStr) - 1; i++) {
    Serial.print(i, DEC);
    Serial.print(" = ");
    Serial.write(minhaStr[i]);
    Serial.println();
  }
  delay(5000);  // espera 5 segundos
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Note que `sizeof` retorna o número total de bytes. Então, para vetores de tipos de dados maiores, como `int`, o loop `for` parece algo do tipo abaixo.

[source,arduino]
----
int meusValores[] = {123, 456, 789};

// this for loop works correctly with an array of any type or size
for (byte i = 0; i < (sizeof(meusValores)/sizeof(meusValores[0])); i++) {
  // fazer algo com meusValores[i]
}
----

Note também que uma string apropriadamente formatada é encerrada com o símbolo NULL, que tem valor ASCII 0.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
