---
title: sizeof()
categories: [ "Variables" ]
subCategories: [ "Utilitários" ]
---

= sizeof

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
O operador sizeof retorna o número de bytes de uma variável, ou o número de bytes ocupados em um vetor.
[%hardbreaks]


[float]
=== Sintaxe
`sizeof(variável)`


[float]
=== Parâmetros
`variável`: uma variável ou vetor de qualquer tipo (ex: int, float, byte)

[float]
=== Retorna
O número de bytes em uma variável ou o número de bytes ocupados em um vetor. (size_t)

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O perador `sizeof` é útil para manipular arrays (tais como strings), onde é conveniente ser possível mudar o tamanho do vetor sem quebrar outras partes do programa.

O programa abaixo imprime um string um caractere de cada vez. Tente mudar o texto da frase.

[source,arduino]
----
char minhaStr[] = "Esse é um teste";
int i;

void setup(){
  Serial.begin(9600);
}

void loop() {
  for (i = 0; i < sizeof(minhaStr) - 1; i++){
    Serial.print(i, DEC);
    Serial.print(" = ");
    Serial.write(minhaStr[i]);
    Serial.println();
  }
  delay(5000); // espera 5 segundos
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Note que `sizeof` retorna o número total de bytes. Então, para os tipos de dados maiores, como ints, o loop for parece algo do tipo abaixo. Note também que uma string apropriadamente formatada é encerrada com o símbolo NULL, que tem valor ASCII 0.

[source,arduino]
----
for (i = 0; i < (sizeof(meusInts)/sizeof(int)); i++) {
  // faz algo com meusInts[i]
}
----

--
// HOW TO USE SECTION ENDS
