---
title: double
categories: [ "Variables" ]
subCategories: [ "Tipos de Dados" ]
---

= double

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Número de Ponto flutuante Double. No UNO e outras placas baseadas no ATMEGA, ocupa 4 bytes. Isto é, nesses a impelmentação do double é exatamente a mesma do float, sem nenhum ganho em precisão.

No Arduino Due e outras placas com SAMD, doubles usam 8 bytes, ou seja, precisão de 64 bits.
[%hardbreaks]


[float]
=== Sintaxe
`double var = val;`


[float]
=== Parâmetros
`var`: nome da variável +
`val`: valor a ser atribuído à variável

--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas e Advertências
Usuários que pegam código de outras fontes que inclua variáveis double pidem desejar examinar o código para conferir se a precisão é diferente do que realmente é alcançado nas placas Arduino baseadas em microcontroladores ATMEGA.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../float[Tipo de dado float] +

--
// SEE ALSO SECTION ENDS
