---
title: int
categories: [ "Variables" ]
subCategories: [ "Tipos de Dados" ]
---

= int

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Ints (integer ou inteiros) são o tipo o tipo de dados primário para armazenamento de números.

No Arduino Uno (e outras placas baseadas em micros ATmega) um int armazena um valor 16-bit (2 bytes). Isso garante um intervalo de -32,768 a 32,767 (um valor mínimo de -2^15 e um valor máximo de (2^15) - 1).
No Arduino Due e outras placas baseadas em micros SAMD (como o MKR1000 e Zero), um int armazena um valor 32-bit (4 bytes). O que garante um intervalo de -2,147,483,648 a 2,147,483,647 (um valor mínimo de -2^31 e um valor máximo de (2^31) - 1).

Variáveis int armazenam números negativos com uma técnica chamada (https://pt.wikipedia.org/wiki/Complemento_para_dois[Complemento de 2]). O bit mais significativo, as vezes chamado de o "bit de sinal", indica que o número é negativo. O resto dos bits são invertidos e 1 é adicionado.

O Arduino cuida dos detalhes nas operações com números negativos por você, tal que operações aritméticas funcionam transparentemente na maneira esperada. No entanto, pode-se haver uma complicação ao lidar com o operador de link:../../../structure/bitwise-operators/bitshiftright/[deslocamento de bits a direita] (>>).
[%hardbreaks]


[float]
=== Sintaxe
`int var = val;`


=== Parâmetros
`var`: nome da variável +
`val`: valor a ser atribuído à variável

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Esse código cria uma variável do tipo integer chamada 'contador', a qual é inicialmente atribuído o valor 0 (zero). A váriavel incrementa em 1 (um) a cada execução do loop e é mostrada no monitor serial.

[source,arduino]
----
int contador = 0;          //cria uma variável integer chamada 'contador'

void setup() {
  Serial.begin(9600);      // usa a porta serial para imprimir o número
}

void loop() {
  contador++;               // soma 1 ao int contador a cada execução do loop
  Serial.println(contador); // Imprime o estado atual do contador
  delay(1000);
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Quando variáveis com  sinal são forçadas a exceder sua capacidade máxima ou mínima, elas _estouram_; ou do Inglês, sofrem _overflow_.  O resultado de um overflow é imprevisível, então isso deve ser evitado.  Um sintoma típico de um overflow é a variável "rolar" de sua capacidade máxima para a mínima ou vice-versa, mas não é sempre o caso.  Se você deseja esse comportamento, use o tipo link:../unsignedint/[unsigned int].

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../constants/integerconstants[Integer Constants] +

--
// SEE ALSO SECTION ENDS
