---
title: long
categories: [ "Variables" ]
subCategories: [ "Tipos de Dados" ]
---

= long


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Variáveis long são variáveis de tamanho extendido para armazenamento de números, armazenam 32 bits (4 bytes), de  -2,147,483,648 a 2,147,483,647.

Ao se fazer cálculos com inteiros, pelo menos um dos números deve ser seguido por um L, forçando-o a ser um long. Veja a página sobre link:../../constants/integerconstants[Constantes Inteiras] para detalhes.
[%hardbreaks]

[float]
=== Sintaxe

`long var = val;`

`var` - o nome da variável long
`val` - o valor dado à variável
[%hardbreaks]
--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
long speedOfLight = 186000L;  // veja a página sobre constantes inteiras para uma explicação sobre o 'L'
----

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../constants/integerconstants[Constantes Inteiras] +

--
// SEE ALSO SECTION ENDS
