---
title: "String()"
categories: [ "Variables" ]
subCategories: [ "Tipos de Dados" ]
---

= String()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Constrói uma instância da classe String. Há múltiplas versões que constroem Strings a partir de diferentes tipos de dados (ex. formatam-nos como uma sequência de caracteres), incluindo:

* uma string constante de caracteres, em aspas duplas (ex. um vetor de caracteres)
* um único caractere constante, em aspas simples
* uma outra instância de um objeto String
* um int constante ou long int
* um int constante ou long int, usando uma base especificada
* uma variável int ou long int
* uma variável int ou long int, usando uma base especificada
* um float ou double, usando um número especificado de casas decimais

Nesse texto, sequências de caracteres são chamadas `strings`, enquanto instâncias da classe String (objetos) são chamados `String`. 

Construir uma String a partir de um número resulta em uma String que contém a representação ASCII desse número. A base padrão é dez, então:
[source,arduino]
----
String thisString = String(13);
----
Fornece a String "13". No entanto, você pode usar outras bases. Por exemplo,


[source,arduino]
----
String thisString = String(13, HEX);
----

que fornece a String "D", que é a representação hexadecimal do valor 13. Ou se você preferir binário,

[source,arduino]
----
String thisString = String(13, BIN);
----

forneca a String "1101", que é a representação binária de 13.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
String(val)
String(val, base)
String(val, decimalPlaces)
----

[float]
=== Parâmetros
`val`:  a variável a ser formatada como String - *Tipos de dados permitidos:* string, char, byte, int, long, unsigned int, unsigned long, float, double +
`base` (opcional): a base na qual formatar valores inteiros 
`decimalPlaces` (*apenas se val é float ou double*): o número desejado de casas decimais

[float]
=== Retorna
Uma instância da classe String.
--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
Todas a seguir são declarações válidas para Strings.
[source,arduino]
----
String stringOne = "Hello String";                     // usando uma string constante
String stringOne =  String('a');                       // convertendo um caractere constante para uma String
String stringTwo =  String("This is a string");        // convertendo uma string constante para um objeto String
String stringOne =  String(stringTwo + " with more");  // concatenando duas strings
String stringOne =  String(13);                        // usando um inteiro constante
String stringOne =  String(analogRead(0), DEC);        // usando um int e uma base especificada (decimal)
String stringOne =  String(45, HEX);                   // usando um int e uma base especificada (hexadecimal)
String stringOne =  String(255, BIN);                  // usando um int e uma base especificada (binário)
String stringOne =  String(millis(), DEC);             // usando um long e uma base especificada
String stringOne =  String(5.698, 3);                  // usando um float e o número de casas decimais
----

--
// HOW TO USE SECTION ENDS


[float]
=== Funções

[role="language"]
#LINGUAGEM# link:../string/functions/charat[charAt()] +
#LINGUAGEM# link:../string/functions/compareto[compareTo()] +
#LINGUAGEM# link:../string/functions/concat[concat()] +
#LINGUAGEM# link:../string/functions/c_str[c_str()] +
#LINGUAGEM# link:../string/functions/endswith[endsWith()] +
#LINGUAGEM# link:../string/functions/equals[equals()] +
#LINGUAGEM# link:../string/functions/equalsignorecase[equalsIgnoreCase()] +
#LINGUAGEM# link:../string/functions/getbytes[getBytes()] +
#LINGUAGEM# link:../string/functions/indexof[indexOf()] +
#LINGUAGEM# link:../string/functions/lastindexof[lastIndexOf()] +
#LINGUAGEM# link:../string/functions/length[length()] +
#LINGUAGEM# link:../string/functions/remove[remove()] +
#LINGUAGEM# link:../string/functions/replace[replace()] +
#LINGUAGEM# link:../string/functions/reserve[reserve()] +
#LINGUAGEM# link:../string/functions/setcharat[setCharAt()] +
#LINGUAGEM# link:../string/functions/startswith[StartsWith()] +
#LINGUAGEM# link:../string/functions/substring[substring()] +
#LINGUAGEM# link:../string/functions/tochararray[toCharArray()] +
#LINGUAGEM# link:../string/functions/toint[toInt()] +
#LINGUAGEM# link:../string/functions/tofloat[toFloat()] +
#LINGUAGEM# link:../string/functions/tolowercase[toLowerCase()] +
#LINGUAGEM# link:../string/functions/touppercase[toUpperCase()] +
#LINGUAGEM# link:../string/functions/trim[trim()] +

[float]
=== Operadores

[role="language"]
#LINGUAGEM# link:../string/operators/elementaccess[[\] (acesso de elementos)]  +
#LINGUAGEM# link:../string/operators/concatenation[+ (concatenação)] +
#LINGUAGEM# link:../string/operators/append[+= (anexação)] +
#LINGUAGEM# link:../string/operators/comparison[== (comparação)] +
#LINGUAGEM# link:../string/operators/greaterthan[> (maior que)] +
#LINGUAGEM# link:../string/operators/greaterthanorequalto[>= (maior ou igual a)] +
#LINGUAGEM# link:../string/operators/lessthan[< (menor que)] +
#LINGUAGEM# link:../string/operators/lessthanorequalto[\<= (menor que ou igual a)] +
#LINGUAGEM# link:../string/operators/differentfrom[!= (diferente de)] +

[role="example"]
#EXEMPLO# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[Tutoriais sobre objetos String (Em Inglês)] +


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
