---
title: unsigned long
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= unsigned long

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Variáveis unsigned long são variáveis de tamanho extendido para armazenamento de números, que armazenam 32 bits (4 bytes). Diferentemente de longs padrão, unsigned longs não guardam números negativos, o que faz com que possam armazenar valores de 0 a 4,294,967,295 (2^32 - 1).
[%hardbreaks]

[float]
=== Sintaxe
`unsigned long var = val;`


=== Parâmetros
`var`: nome da variável +
`val`: valor a ser atribuído à variável
[%hardbreaks]

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo cria uma variável do tipo long para guardar o número de milissegundos desde que o programa iniciou.

[source,arduino]
----
unsigned long time; //variável do tipo long

void setup() {
  Serial.begin(9600);
}

void loop() {
  Serial.print("Time: ");
  time = millis();
  //imprime o tempo desde que o programa iniciou, em milissegundos
  Serial.println(time);
  // espera um segundo, para não enviar quantidades massivas de dados
  delay(1000);
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../constants/integerconstants[Constantes Inteiras] +

--
// SEE ALSO SECTION ENDS
