---
title: unsigned char
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= unsigned char


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Um tipo de dado sem sinal, que ocupa um byte na memória. O mesmo que o tipo de dado link:../byte[byte]. O tipo de dado unsigned char armazena valores de 0 a 255.

Para consistência do estilo de programação Arduino, o tipo de dado byte é preferido.
[%hardbreaks]


[float]
=== Sintaxe
`unsigned char var = val;`


[float]
=== Parâmetros
`var`: nome da variável +
`val`: valor a ser atribuído à variável

--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O trecho de código abaixo cria uma variável do tipo unsigned char

[source,arduino]
----
unsigned char myChar = 240;
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../../functions/communication/serial/println[Serial.println] +

--
// SEE ALSO SECTION ENDS
