---
title: ">="
title_expanded: greater than or equal to
categories: [ "Data Types" ]
subCategories: [ "StringObject Operator" ]
---

= >= Greater Than Or Equal To

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Testa se a String à esquerda é maior que, ou igual, a String à direita. Esse operador avalia Strings em ordem alfabética, no primeiro caractere no qual as duas diferem. Então, por exemplo "b" >= "a" e "2" >= "1", mas "999" >= "1000" porque 9 vem depois de 1.

Cuidado: Operadores de comparação de Strings podem ser confusos quando você está comparando Strings numéricas, porque os numerais são tratados como strings e não números. Se você precisa comparar números numericamente, compare-os como ints, floats ou longs, e não como Strings.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
string1 >= string2
----

[float]
=== Parâmetros
`string1, string2`: variáveis do tipo String


[float]
=== Retorna
`true`: se a String à esquerda é maior que, ou igual, a String à direita 

`false`: do contrário
--

// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
#EXEMPLO# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[Tutoriais String (Em Inglês)] +
--
// SEE ALSO SECTION ENDS
