---
title: ">="
title_expanded: greater than or equal to
categories: [ "Data Types" ]
subCategories: [ "StringObject Operator" ]
---





= >= Greater Than Or Equal To


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Tests if the string on the left is greater than the string on the right. This operator evaluate strings in alphabetical order, on the first character where the two differ. So, for example "b" >= "a" and "2" >= "1", but "999" >= "1000" because 9 comes after 1.

Caution: String comparison operators can be confusing when you're comparing numeric strings, because the numbers are treated as strings and not as numbers. If you need to compare numbers numerically, compare them as ints, floats, or longs, and not as Strings.

[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
string1 >= string2
----

[float]
=== Parâmetros
`string1, string2`: variables of type String


[float]
=== Retorna
`true`: if string1 is greater than or equal to string2

`false`: otherwise
--

// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
#EXEMPLO# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[Tutoriais String (Em Inglês)] +
--
// SEE ALSO SECTION ENDS