---
title: else
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---

= if...else

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
A combinação `if...else` permite maior controle sobre o fluxo de código que o comando mais básico link:../if[if], por permitir múltiplos testes serem agrupados juntos. Uma cláusula `else` (se presente) será executada se a condição do comando `if` resulta em `false`. O `else` pode proceder outro teste `if`, tal que múltiplos, testes mutualmente exclusivos podem ser executados ao mesmo tempo.
[%hardbreaks]

Cada teste irá proceder para o próximo até um teste que resulte em verdadeiro seja encontrado. Quando esse teste for encontrado, o bloco de código correspondente a condição é executado, e o programa então continua a partir da linha seguinte a estrutura if-else completa. Se nenhum teste resultar em verdadeiro, o bloco `else` padrão é executado, se um estiver presente, que dita o comportamento padrão.
[%hardbreaks]

Note que um bloco `else if` pode ser usado sem um bloco `else` no final e vice-versa. Um número praticamente ilimitado de blocos `else if` conectados é permitido.

[float]
=== Sintaxe
[source,arduino]
----
if (condição1) {
  // faz coisa A
}
else if (condição2) {
  // faz coisa B
}
else {
  // faz coisa C
}
----
--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
=== Código de Exemplo
Abaixo um trecho de código de um sistema de controle de temperatura
[source,arduino]
----
if (temperatura >= 70) {
  //Perigo! Desligar o sistema
}
else if (temperatura >= 60 && temperatura < 70) {
  //Cuidado! Requerida a atenção do usuário
}
else {
  //Seguro! Continue as tarefas usuais...
}
----

--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
