---
title: goto
categories: [ "Structure" ]
subCategories: [ "Estruturas de Controle" ]
---

= goto


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Transfere o fluxo do programa para um ponto rotulado no código.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
rótulo:

goto rótulo; // envia o fluxo do programa de volta para o rótulo
----

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
O código abaixo "foge" de dentro de todos os laços caso a leitura no pino analógico 0 seja maior que 250. 
[source,arduino]
----
for(byte r = 0; r < 255; r++){
    for(byte g = 255; g > 0; g--){
        for(byte b = 0; b < 255; b++){
            if (analogRead(0) > 250){ goto cancelar;}
            // mais comandos ...
        }
    }
}

cancelar:
----
[%hardbreaks]

[float]
=== Notas e Advertências
O uso do `goto` é *desencorajado* na programação em C, e alguns autores de livros sobre a linguagem C afirmam que o uso do comando `goto` nunca é necessário, mas se usado judiciosamente ele pode simplificar certos programas. A pela qual muitos programadores desaprovam o uso do goto é que com o uso descuidado de comando `goto`, é fácil criar um programa com fluxo indefinido, que não pode ser depurado.

Tendo dito isso, há algumas instâncias onde o comando `goto` pode ser considerado, por simplificar o código. Uma dessas situações é sair de laços link:../for[for] profundamente aninhados, ou blocos link:../if[if], em determinada condição.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também
[role="language"]

--
// SEE ALSO SECTION ENDS
