---
title: if
categories: [ "Structure" ]
subCategories: [ "Estruturas de Controle" ]
---

= if


// OVERVIEW SECTION STARTS
[#overview]
--
[float]
=== Descrição
O comando `if` checa uma condição e executas o comando a seguir ou um bloco de comandos delimitados por chaves, se a condição é verdadeira ('true').
[%hardbreaks]

[float]
=== Sintaxe
[source,arduino]
----
if (condição) {
  //comando(s)
}
----

[float]
=== Parâmetros
condição: uma expressão booleana, isto é, que pode resultar apenas em `true` ou `false`

[float]
=== Código de Exemplo

As chaves podem ser omitidas depois de um comando `if`. Se isso é feito, a próxima linha (definida pelo ponto e vírgula) é interpretada como o único comando condicional. Para mais de um comando, use as chaves para delimitar o bloco de comandos.
[%hardbreaks]

[source,arduino]
----
if (x > 120) {
  digitalWrite(pinoLED, HIGH);
}

if (x > 120) {
  digitalWrite(pinoLED, HIGH);
}

if (x > 120) {
  digitalWrite(pinoLED, HIGH);
}

if (x > 120) {
  digitalWrite(pinoLED1, HIGH);
  digitalWrite(pinoLED2, HIGH);
} // todas as formas acima estão corretas
----
[%hardbreaks]


[float]
=== Notas e Advertências
As expressões sendo testadas dentro dos parênteses geralmente requerem o uso de um ou mais dos operadores mostrados abaixo.
[%hardbreaks]

*Operadores de comparação:*

 x == y (x é igual a y)
 x != y (x é diferente de y)
 x <  y (x é menor que y)
 x >  y (x maior que y)
 x <= y (x é menor ou igual a y)
 x >= y (x é maior ou igual a y)


Cuidado para não usar acidentalmente o símbolo de igual simples (ex. `if (x = 10)` ). O símbolo de igual simples é o operador de atribuição, se atribui 10 a `x` (coloca o valor 10 na variável `x`). Em vez disso, o símbolo de igual duplo (ex. `if (x == 10)` ) deve ser usado, que é o operador de comparação, e testa _se_ `x` é igaul a 10 ou não. O último é apenas verdadeiro se `x` é igual a 10, enquanto o primeiro comando mostrado sempre resultará em verdadeiro.

Isso acontece porque a linguagem C++ interpreta `if (x=10)` da seguinte forma: 10 é atribuído a `x` (Lembre que o símbolo de igual simples é o (http://arduino.cc/en/Reference/Assignment[operador de atribuição^])), então `x` agora contém 10. então o comando 'if' testa 10, o que sempre resulta `true`, desde que qualquer número diferente de zero resulta em `true`. Consequentemente, `if (x = 10)` irá sempre resultar em `true`, o que não é desejável ao se usar um comando 'if'. Além disso, a variável `x` irá receber o valor 10, o que também é indesejado.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
