---
title: switch...case
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---

= comando switch...case


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Da mesma forma que o comando link:../if[if], o comando link:../switchcase[switch case] controla o fluxo do programa permitindo ao programador especificar código diferente para ser executado em várias condições. Em particular, um comando `switch` compara o valor de uma variável aos valores especificados nos comandos `case`. Quando um comando `case` é encontrado cujo valor é igual ao da variável, o código para esse comando `case` é executado.
[%hardbreaks]

A palavra-chave link:../break[break] interrompe o comando switch, e é tipicamente usada no final de cada `case`. Sem um comando `break`, o comando `switch` irá continuar a executar as expressões seguintes (desnecessariamente) até encontrar um break, ou até o final do comando switch ser alcançado.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
switch (var) {
  case valor1:
    // comando(s)
    break;
  case valor2:
    // comando(s)
    break;
  default:
    // comando(s)
    break;
}
----


[float]
=== Parâmetros
`var`: uma variável para ser comparada com os vários cases. *Tipos de dados permitidos:* int, char +
`valor1`, `valor2`: constantes. *Tipos de dados permitidos:* int, char

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
switch (var) {
  case 1:
    // faz algo quando var é igual a 1
    break;
  case 2:
    // faz algo quando var é igual a 1
    break;
  default:
    // Se nenhum dos anteriores, faz o caso padrão default
    // default é opcional
    break;
}

----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTIN BEGINS
[#see_also]
--

[float]
=== Ver Também
[role="language"]

--
// SEE ALSO SECTION ENDS
