---
title: analogRead()
categories: [ "Functions" ]
subCategories: [ "Entradas e Saídas Analógicas" ]
---

:source-highlighter: pygments
:pygments-style: arduino


= analogRead()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Lê o valor de um pino analógico especificado. A placa Arduino possui um conversor analógico-digital de 6 canais (8 canais nos Mini e Nano, 16 no Mega). Isso significa que este irá mapear tensões entre 0 e 5 volts para valores inteiros entre 0 e 1023. Isso permite uma resolução entre leituras de: 5 volts / 1024 unidades, ou .0049 volts (4.9 mV) por unidade. O intervalo de tensões de entrada pode ser mudado usando-se a função link:../analogReference[analogReference()].

Ler um valor analógico leva em torno de 100 microssegundos (0.0001 s), então a taxa de leitura máxima é aproximadamente 10,000 leituras por segundo.
[%hardbreaks]


[float]
=== Sintaxe

`analogRead(pino)`

[float]
=== Parâmetros
`pino`: o número do pino de entrada analógica o qual se quer ler (0 a 5 na maioria das placas, 0 a 7 nos Mini e Nano, 0 a 15 no Mega)

[float]
=== Retorna
int(0 a 1023)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo lê o valor de um pino de entrada analógica e mostra seu valor na porta serial.

[source,arduino]
----
int analogPin = 3;     // terminal do meio de um potênciometro conectado ao pino analógico 3
                       // terminais mais externos são conectados um no ground e o outro em +5V
int val = 0;           // variável para guardar o valor lido

void setup()
{
  Serial.begin(9600);              //  configura a porta serial
}

void loop()
{
  val = analogRead(analogPin);     // lê o pino de entrada
  Serial.println(val);             // imprime o valor na porta serial
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Se o pino de entrada analógica não estiver conectado a nada, o valor retornado por analogRead() irá flutuar baseado numa gama de fatores (ex. o valor de outros pinos analógicos, quão próxima suu mão está da placa, etc.).

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
* #LINGUAGEM# link:../../arduino-due-only/analogreadresolution[analogReadResolution()]
* #LINGUAGEM# https://www.arduino.cc/en/Tutorial/AnalogInputPins[Tutorial: Pinos de entrada analógica (Em Inglês)]
--
// SEE ALSO SECTION ENDS
