---
title: analogReference()
categories: [ "Functions" ]
subCategories: [ "Entradas e Saídas Analógicas" ]
---


//


= analogReference()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Configura a tensão de referência para a entrada analógica (o valor máximo do intervalo de entrada). As opções são:

* DEFAULT: a referência analógica padrão de 5 volts (em placas Arduino de 5V) ou 3.3 volts (em placas Arduino de 3.3V)
* INTERNAL: uma referência interna, igual a 1.1 volts no ATmega168 ou ATmega328P e 2.56 volts no ATmega8 (Não disponível no Arduino Mega)
* INTERNAL1V1: uma referência interna de 1.1V (apenas Arduino Mega)
* INTERNAL2V56: uma referência interna de 2.56V (apenas Arduino Mega)
* EXTERNAL: a tensão aplicada ao pino AREF (0 a 5V apenas) é usada como referência.
[%hardbreaks]


[float]
=== Sintaxe
`analogReference(tipo)`


[float]
=== Parâmetros
`tipo`: qual tipo de referência usar (DEFAULT, INTERNAL, INTERNAL1V1, INTERNAL2V56 ou EXTERNAL).

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas e Advertências
Após mudar-se a referência analógica, as primeiras leituras com `analogRead()` podem ser imprecisas.

*Não use menos que 0V ou mais que 5V como tensão de referência externa no pino AREF! Se você está usando uma referência externa no pino AREF, deve configurar a referência como EXTERNAL antes de chamar `analogRead()`.* Do contrário, você irá curto-circuitar a tensão de referência ativa (gerada internamente) e o pino AREF, possivelmente danificando o microcontrolador da sua placa Arduino.

Alternativamente, você pode conectar a tensão de referência externa ao pino AREF através de um resistor de 5K ohm, permitindo-lhe trocar entre tensões de referência externas e internas. Note que o resistor irá alterar a tensão usada como referência, pois há um resistor interno de 32K ohm no pino AREF. Os dois em conjunto agem como um divisor de tensão, então, por exemplo, 2.5V aplicados através do resistor irão fornecer 2.5 * 32 / (32 + 5) = ~2.2V ao pino AREF.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
* #EXEMPLO# http://arduino.cc/en/Tutorial/AnalogInputPins[Descrição dos pinos analógicos de entrada (Em Inglês)]

--
// SEE ALSO SECTION ENDS
