---
title: constrain()
categories: [ "Functions" ]
subCategories: [ "Funções Matemáticas" ]
---

= constrain(x, a, b)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Restringe um número a ficar dentro de um intervalo.
[%hardbreaks]


[float]
=== Sintaxe
`constrain(x, a, b)`


[float]
=== Parâmetros
`x`: o número a se restringir, qualquer tipo de dado

`a`: o extremo inferior do intervalo, qualquer tipo de dado

`b`: o extremo superior do intervalo, qualquer tipo de dado

[float]
=== Retorna
x: se x está entre a e b

a: se x é menor que a

b: se x é maior que b

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código limita os valores de uma variável com a leitura de um sensor entre 10 e 150.

[source,arduino]
----
sensVal = constrain(sensVal, 10, 150);  // limita os valores entre 10 e 150
----

[float]
=== Notas e Advertências
Por causa da forma como a função `constrain()` é implementada, evite usar outras funções dentro dos parênteses, pois isso pode levar a resultados incorretos.

Esse código gerará resultados incorretos:
[source,arduino]
----
int constrainedInput = constrain(Serial.parseInt(), minimumValue, maximumValue);   // evite isso
----

Faça essa forma:
[source,arduino]
----
int input = Serial.parseInt();  // manter outras operações fora da função constrain()
int constrainedInput = constrain(input, minimumValue, maximumValue);
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
