---
title: max()
categories: [ "Functions" ]
subCategories: [ "Funções Matemáticas" ]
---

= max(x, y)

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Calcula o maior de dois números.
[%hardbreaks]


[float]
=== Sintaxe
`max(x, y)`


[float]
=== Parâmetros
`x`: o primeiro número, qualquer tipo de dado

`y`: o segundo número, qualquer tipo de dado

[float]
=== Retorna
O maior dos dois números passados para a função.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código garante que o valor de sensVal seja pelo menos 20.

[source,arduino]
----
sensVal = max(sensVal, 20); // atribui a sensVal o maior valor, seja sensVal ou 20
                            // (efetivamente garantindo que sensVal seja ao menos 20)
----
[%hardbreaks]

[float]
=== Notas e Advertências
Talvez contraintuitivamente, `max()` é constantemente usada para restringir o extremo inferior do intervalo de uma variável, enquanto `min()` é usado para restringir o extremo superior do intervalo.

Por causa da forma em que a função `max()` é implementada, evite usar outras funções dentro dos parênteses, isso pode levar a resultados incorretos.
[source,arduino]
----
max(a--, 0);  // evitar isso - causa resultados incorretos

max(a, 0);    // ao invés disso, usar esta forma
a--;          // manter a aritmética fora da função
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
