---
title: min()
categories: [ "Functions" ]
subCategories: [ "Funções Matemáticas" ]
---

= min(x, y)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Calcula o menor de dois números.
[%hardbreaks]


[float]
=== Sintaxe
`min(x, y)`


[float]
=== Parâmetros
`x`: o primeiro número, qualquer tipo de dado

`y`: o segundo número, qualquer tipo de dado

[float]
=== Retorna
O menor dos dois números passados para a função.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== ECódigo de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código garante que o valor de sensVal nunca é maior que 100.

[source,arduino]
----
sensVal = min(sensVal, 100); // atribui a sensVal o menor valor, seja sensVal ou 100
                             // garantindo que esse nunca seja maior que 100.
----
[%hardbreaks]

[float]
=== Notas e Advertências
Talvez contraintuitivamente, `max()` é constantemente usada para restringir o extremo inferior do intervalo de uma variável, enquanto `min()` é usado para restringir o extremo superior do intervalo.

Por causa da forma em que a função `max()` é implementada, evite usar outras funções dentro dos parênteses, isso pode levar a resultados incorretos.
[source,arduino]
----
min(a++, 100);   // evitar isso - causa resultados incorretos

min(a, 100);     // ao invés disso, usar esta forma
a++;             // manter a aritmética fora da função
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
