---
title: pow()
categories: [ "Functions" ]
subCategories: [ "Funções Matemáticas" ]
---

= pow(base, exponent)

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Calcula o valor de um número elevado a uma potência. `Pow()` pode ser usada para transformar um número em uma potência fracionária. Isso pode ser útil para gerar mapeamentos exponenciais de valores ou curvas.
[%hardbreaks]


[float]
=== Sintaxe
`pow(base, expoente)`


[float]
=== Parâmetros
`base`: o número (`float`)

`expoente`: a potência a qual o número deve ser elevado (`float`)

[float]
=== Retorna
O resultado da exponenciação. (`double`)

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Veja a função (http://arduino.cc/playground/Main/Fscale[fscale (Em Inglês)]) no Arduino Playground.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="definition"]
#DEFINIÇÃO# link:../../../variables/data-types/float[float] +
#DEFINIÇÃO# link:../../../variables/data-types/double[double]

--
// SEE ALSO SECTION ENDS
