---
title: const
categories: [ "Variables" ]
subCategories: [ "Variable Scope & Qualifiers" ]
---

= palavra-chave const

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
A palavra-chave `const` é uma abreviação de constante. É um _qualificador_  de variáveis que modifica o comportamento da variável, fazendo com que a variável seja de "_apenas-leitura_". Isso significa que a variável pode ser usada como qualquer outra variável de seu tipo, mas seu valor não pode ser mudado. Você terá um erro de compilação se tentar atribuir um valor a uma variável `const`.

Constantes definidas com a palavra chave `const` obedecem as regras dos link:../scope[escopos de variáveis] que governam variáveis. Isso, e as armadilhas de se usar `#define`, fazem com que o modificador `const` um método superior de se definir constantes e é favorecido em lugar de se usar link:../../../structure/further-syntax/define[`#define`].
[%hardbreaks]

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
const float pi = 3.14;
float x;
// ....
x = pi * 2; // constantes podem ser usadas em cálculos
pi = 7; // ilegal - você não pode modificar o valor de uma constante
----
[%hardbreaks]

[float]
=== Notas e Advertências
*`#define` ou `const`*

Você pode usar ambos `const` ou `#define` para criar constantes numéricas ou strings constantes. Para link:../../data-types/array[vetores], você irá precisar usar `const`. Em geral, `const` é favorecido em lugar de `#define` ao se definir constantes.


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../../structure/further-syntax/define[#define] +

--
// SEE ALSO SECTION ENDS
