---
title: escopo
categories: [ "Variables" ]
subCategories: [ "Escopo de Variáveis e Qualificadores" ]
---

= Escopo de variáveis


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Variáveis na linguagem de programação C, a qual o Arduino usa, possuem uma propriedade chamada escopo. Isso contrasta com antigas versões de linguagens como o BASIC onde toda variável era uma variável _global_.

Uma variável global é uma que pode ser vista por todas as funções de um programa. Diferentemente, variáveis locais são visíveis apenas às funções nas quais são declaradas. No ambiente Arduino, qualquer variável declarada fora de uma função (ex. setup(), loop(), etc. ), é uma variável _ global_.

Quando programas começam a ficar muito longos e complexos, variáveis locais são uma forma útil de garantir que apenas uma função tenha acesso as suas próprias variáveis. Isso previne erros de programação quando uma função inadvertidamente modifica variáveis usadas por outra função.

Às vezes também é vantajoso declarar e inicializar uma variável dentro de um loop `for`. Isso cria uma variável que pode ser acessada apenas dentro do próprio bloco do loop `for`. 
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
int gPWMval;  // qualquer função poderá acessar essa variável

void setup()
{
  // ...
}

void loop()
{
  int i;    // "i" é "visível" apenas dentro de "loop"
  float f;  // "f" é "visível" apenas dentro de "loop"
  // ...

  for (int j = 0; j <100; j++){
    // a variável j pode ser acessada apenas dentro das chaves do loop for
  }

}
----
[%hardbreaks]


--
// HOW TO USE SECTION ENDS
