---
title: "isAlpha()"
categories: [ "Functions" ]
subCategories: [ "Caracteres" ]
---





= isAlpha(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Analisa se um caractere é alfabético (isto é, se é uma letra). Retorna true (verdadeiro) se thisChar contém uma letra. 
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
isAlpha(thisChar)
----

[float]
=== Parâmetros
`thisChar`: variável. *Tipos de dados permitidos:* char

[float]
=== Retorna
`true`: se thisChar é um caractere alfabético.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
O código a seguir testa se uma variável chamada this é uma letra.
[source,arduino]
----
if (isAlpha(this)) {  // testa se a variável this é uma letra
  Serial.println("The character is alpha");
}
else {
  Serial.println("The character is not alpha");
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM#  link:../../../variables/data-types/char[char]
#LINGUAGEM#  link:../../../structure/control-structure/if[if (operadores condicionais)]
#LINGUAGEM#  link:../../../structure/control-structure/while[while (operadores condicionais)]
#LINGUAGEM# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
