---
title: "isAlphaNumeric()"
categories: [ "Functions" ]
subCategories: [ "Caracteres" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= isAlphaNumeric(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Analisa se um caractere é alfanumérico (isto é, uma letra ou um número). Retorna true (verdadeiro) se thisChar contém ou uma letra ou um número. 
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
`isAlphaNumeric(thisChar)`
----

[float]
=== Parâmetros
`thisChar`: variável. *Tipos de dados permitidos:* char

[float]
=== Retorna
`true`: se a variável thisChar é uma letra ou um número..

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
if (isAlphaNumeric(this))      // testa se this é uma letra ou um número
{
	Serial.println("The character is alphanumeric");
}
else
{
	Serial.println("The character is not alphanumeric");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
* #LINGUAGEM#  link:../../../variables/data-types/char[char]
* #LINGUAGEM#  link:../../../structure/control-structure/if[if (operadores condicionais)]
* #LINGUAGEM#  link:../../../structure/control-structure/while[while (operadores condicionais)]
* #LINGUAGEM# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
