---
title: "isPrintable()"
categories: [ "Functions" ]
subCategories: [ "Caracteres" ]
---





= isPrintable(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Analisa se uma caractere é imprimível (isto é, qualquer caractere que produz uma saída, até mesmo um espaço). Retorna true se thisChar é imprimível. Por impimível diz-se os caracteres que pode ser impressos, como letras e números. Alguns caracteres são para controle e não podem ser impressos como o new line (`'\n'`) e o tab (`'\t'`). 
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
isPrintable(thisChar)
----

[float]
=== Parâmetros
`thisChar`: variável. *Tipos de dados permitidos:* char

[float]
=== Retorna
`true`: se thisChar é imprimível.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
if (isPrintable(meuChar)) {  // testa se meuChar é imprimível
  Serial.println("The character is printable");
}
else {
  Serial.println("The character is not printable");
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
* #LINGUAGEM#  link:../../../variables/data-types/char[char]
* #LINGUAGEM#  link:../../../structure/control-structure/if[if (operadores condicionais)]
* #LINGUAGEM#  link:../../../structure/control-structure/while[while (operadores condicionais)]
* #LINGUAGEM# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
