---
title: "isPunct()"
categories: [ "Functions" ]
subCategories: [ "Caracteres" ]
---





= isPunct(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Analisa se uma caractere é pontuação (isto é, uma vírgula, um ponto-e-vírgula, um ponto de exlamação etc). Retorna true se thisChar é um caractere de pontuação. 
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
isPunct(thisChar)
----

[float]
=== Parâmetros
`thisChar`: variável. *Tipos de dados permitidos:* char

[float]
=== Retorna
`true`: se thisChar é um caractere de pontuação

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
if (isPunct(this))      // testa se this é um caractere de pontuação
{
	Serial.println("The character is a punctuation");
}
else
{
	Serial.println("The character is not a punctuation");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
* #LINGUAGEM#  link:../../../variables/data-types/char[char]
* #LINGUAGEM#  link:../../../structure/control-structure/if[if (operadores condicionais)]
* #LINGUAGEM#  link:../../../structure/control-structure/while[while (operadores condicionais)]
* #LINGUAGEM#  link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
