---
title: "isWhitespace()"
categories: [ "Functions" ]
subCategories: [ "Caracteres" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= isWhitespace(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Analisa se um caractere é um espaço em branco, isto é o próprio caractere de espaço (' '), formfeed ('\f'), nova linha ('\n'), retorno ('\r'), tab horizontal tab ('\t') e tab vertical ('\v')). 
Retorna true se thisChar contém um espaço em branco. 
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
`isWhitespace(thisChar)`
----

[float]
=== Parâmetros
`thisChar`: variável. *Tipos de dados permitidos:* char

[float]
=== Retorna
`true`: se thisChar é um caractere de espaço em branco.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
if (isWhitespace(this))      // testa se this é um caractere de espaço em branco
{
	Serial.println("The character is a white space");
}
else
{
	Serial.println("The character is not a white space");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
* #LINGUAGEM#  link:../../../variables/data-types/char[char]
* #LINGUAGEM#  link:../../../structure/control-structure/if[if (operadores condicionais)]
* #LINGUAGEM#  link:../../../structure/control-structure/while[while (operadores condicionais)]
* #LINGUAGEM# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
