---
title: "*"
title_expanded: desreferência
categories: [ "Structure" ]
subCategories: [ "Operadores para Ponteiros" ]
---

= * Operador de Desreferência

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Desreferência é uma das características da linguagem C para uso especificamente com ponteiros. O operador `*` (asterisco) é utilizado para esse propósito. Se `p` é um ponteiro, então `*p` representa o valor contido no endereço apontado por `p`.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
int *p;         // declara um ponteiro para uma variável do tipo int
int i = 5;
int resultado = 0;
p = &i;         // agora 'p' contém o endereço de 'i'
resultado = *p; // 'resultado' recebe o valor contido no endereço apontado por 'p'
                // isto é, recebe o valor de 'i', que é 5
----
[%hardbreaks]

[float]
=== Notas e Advertências
Ponteiros são um dos assuntos mais complicados para iniciantes na linguagem C aprenderem, e é possível escrever a grande maioria dos sketches Arduino sem nunca encontrar ponteiros. No entanto, para manipular certas estruturas de dados, o uso de ponteiros pode simplificar o código. O conhecimento da manipulação de ponteiros é vantajoso de se ter no seu kit de ferramentas.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

[role="definition"]
#DEFINIÇÃO#  https://pt.wikipedia.org/wiki/Ponteiro_(programa%C3%A7%C3%A3o)[Ponteiros^] +

--
// SEE ALSO SECTION ENDS
