---
title: "^="
title_expanded: atribuição por ou exclusivo
categories: [ "Structure" ]
subCategories: [ "Operadores de Atribuição Composta" ]
---

= |= Atribuição por OU EXCLUSIVO


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
O operador de atribuição composta bitwise OU EXCLUSIVO `^=` é frequentemente usado com uma variável e uma constante para "inverter" (ou trocar) bits particulares de uma variável.
[%hardbreaks]

Uma revisão do operador bitwise OU EXCLUSIVO `^`:

   0  0  1  1    operando1
   0  1  0  1    operando2
   ----------
   0  1  1  0    (operando1 ^ operando2) - resultado retornado
[%hardbreaks]

[float]
=== Sintaxe
[source,arduino]
----
x ^= y; // equivalente a x = x ^ y;
----

[float]
=== Parâmetros
`x`: variável. *Tipos de dados permitidos:* char, int, long +
`y`: variável ou constante. *Tipos de dados permitidos:* char, int, long
--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
Bits que são operados através do OU OEXCLUSIVO com 0 não são mudados, então se meuByte é uma variável byte:
[source,arduino]
----
meuByte ^ B00000000 = meuByte;
----

Bits que são operados através do OU EXCLUSIVO com 1 são invertidos, então:
[source,arduino]
----
meuByte ^ B11111111 = ~meuByte;
----
[%hardbreaks]

[float]
=== Notas e Advertências
Porque estamos lidando com bits em um operador bitwise, é conveniente usar o modificador binário com constantes na representação. Os números ainda são os mesmos em outras representações, só não são tão fáceis de entender. Também, B00000000 é mostrado para claridade, mas zero em qualquer outro formato é zero.
[%hardbreaks]

Consequentemente, para inverter os bits 0 e 1 de um variável ao mesmo tempo, deixando o resto da variável intocado, use o operador de atribuição por bitwise OU EXCLUSIVO (^=) com a constante B00000011

   1  0  1  0  1  0  1  0    variável
   0  0  0  0  0  0  1  1    máscara
   ----------------------
   1  0  1  0  1  0  0  1

    bits intactos
                     bits invertidos


Abaixo a mesma representação com os bits da variável substituidos pelo símbolo x. ~x representa o complemento de x.

   x  x  x  x  x  x  x  x    variável
   0  0  0  0  0  0  1  1    máscara
   ----------------------
   x  x  x  x  x  x ~x ~x

    bits intactos
                     bits invertidos

Então:
[source,arduino]
----
myByte = B10101010;
myByte ^= B00000011 == B10101001;
----

--
// HOW TO USE SECTION ENDS




//SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM#  link:../../bitwise-operators/bitwisexor[^ OU EXCLUSIVO Bitwise]

--
// SEE ALSO SECTION ENDS
