---
title: "|="
title_expanded: atribuição por ou
categories: [ "Structure" ]
subCategories: [ "Compound Operators" ]
---

= |= Atribuição por OU


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
O operador de atribuição composta bitwise OU  `|=` é frequentemente usado com uma variável e uma constante para "setar" (mudar pra 1) bits particulares em uma variável.
[%hardbreaks]

Uma revisão do operador bitwise OU `|`:

   0  0  1  1    operando1
   0  1  0  1    operando2
   ----------
   0  1  1  1    (operando1 | operando2) - resultado retornado
[%hardbreaks]

[float]
=== Sintaxe
[source,arduino]
----
x |= y; // equivalente a x = x | y;
----

[float]
=== Parâmetros
`x`: variável. *Tipos de dados permitidos:* char, int, long +
`y`: variável ou constante. *Tipos de dados permitidos:* char, int, long

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
Bits que são operados através do OU com 0 não são mudados, então se meuByte é uma variável byte:
[source,arduino]
----
meuByte | B00000000 = meuByte;
----

Bits que são operados através do OU com 1 são mudados para 1, então:
[source,arduino]
----
meuByte | B11111111 = B11111111;
----
[%hardbreaks]

[float]
=== Notas e Advertências
Porque estamos lidando com bits em um operador bitwise, é conveniente usar o modificador binário com constantes na representação. Os números ainda são os mesmos em outras representações, só não são tão fáceis de entender. Também, B00000000 é mostrado para claridade, mas zero em qualquer outro formato é zero.
[%hardbreaks]

Consequentemente - para setar os bits 0 e 1 de um variável, ao mesmo tempo deixando o resto da variável intocado, useo o operador de atribuição por bitwise OU  (|=) com a constante B00000011

   1  0  1  0  1  0  1  0    variável
   0  0  0  0  0  0  1  1    máscara
   ----------------------
   1  0  1  0  1  0  1  1

    bits intactos
                     bits mudados para 1


Abaixo a mesma representação com os bits da variável substituidos pelo símbolo x

   x  x  x  x  x  x  x  x    variável
   0  0  0  0  0  0  1  1    máscara
   ----------------------
   x  x  x  x  x  x  1  1

    bits intactos
                     bits mudados para 1

Então:
[source,arduino]
----
meuByte = B10101010;
meuByte |= B00000011; // igual a B10101011;
----

--
// HOW TO USE SECTION ENDS




//SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM#  link:../../bitwise-operators/bitwiseor[| Bitwise OU] +

--
// SEE ALSO SECTION ENDS
