---
title: interrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---





= interrupts()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Reativa interrupções (quando elas tiverem sido desativadas por link:../nointerrupts[nointerrupts()]. Interrupções permitem certas tarefas importantes acontecerem ao fundo e são, por padrão, ativadas. Algumas funções não irão funcionar enquanto as interrupções estiverem desativadas, e dados recebidos podem ser ignorados. Interrupções podem levemente interferir no timing do código, no entanto, e podem ser desativadas em seções particulamente críticas do código.
[%hardbreaks]


[float]
=== Sintaxe
`interrupts()`


[float]
=== Parâmetros
Nothing

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo mostra como desativar e reativar interrupções.

[source,arduino]
----
void setup() {}

void loop()
{
  noInterrupts();
  // código crítico e sensível ao tempo aqui
  interrupts();
  // códigos regulares aqui
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver também

[role="language"]
#LINGUAGEM# link:../../external-interrupts/attachinterrupt[attachInterrupts()] +
#LINGUAGEM# link:../../external-interrupts/detachinterrupt[detachInterrupts()]

--
// SEE ALSO SECTION ENDS
