---
title: noInterrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---

= noInterrupts()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Desativa interrupções (você pode reativá-las com `interrupts()`). Interrupções permitem certas tarefas importantes acontecerem ao fundo e são, por padrão, ativadas. Algumas funções não irão funcionar enquanto as interrupções estiverem desativadas, e dados recebidos podem ser ignorados. Interrupções podem levemente interferir no timing do código, no entanto, e podem ser desativadas em seções particulamente críticas do código.
[%hardbreaks]


[float]
=== Sintaxe
`noInterrupts()`

[float]
=== Parâmetros
Nothing

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo mostra como desativar e reativar interrupções.

[source,arduino]
----
void setup() {}

void loop() {
  noInterrupts();
  // código crítico e sensível ao tempo aqui
  interrupts();
  // códigos regulares aqui
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
