---
title: bitWrite()
categories: [ "Functions" ]
subCategories: [ "Bits e Bytes" ]
---





= bitWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Escreve em um bit especificado de um valor numérico.
[%hardbreaks]


[float]
=== Sintaxe
`bitWrite(x, n, b)`


[float]
=== Parâmetros
`x`: a variável numérica cujo bit se deseja escrever

`n`: qual bit do número a ser escrito, começando em 0 para o bit menos significativo (mais à direita)

`b`: o valor a ser escrito no bit (0 ou 1)

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
Demonstrates the use of bitWrite by printing the value of a variable to the Serial Monitor before and after the use of `bitWrite()`.


[source,arduino]
void setup() {
  Serial.begin(9600);
  while (!Serial) {}  // wait for serial port to connect. Needed for native USB port only
  byte x = 0b10000000;  // the 0b prefix indicates a binary constant
  Serial.println(x, BIN); // 10000000
  bitWrite(x, 0, 1);  // write 1 to the least significant bit of x
  Serial.println(x, BIN); // 10000001
}

void loop() {}
----
[%hardbreaks]
--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
