---
title: randomSeed()
categories: [ "Functions" ]
subCategories: [ "Random Numbers" ]
---

= randomSeed(seed)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`randomSeed()` inicializa o gerador de números pseudoaleatórios, fazendo o começar em um ponto arbitrário em sua sequência aleatória. Essa sequência, enquanto muito longa, e aleatória, é sempre a mesma.

Se é importante que uma sequência de valores gerados por `random()` seja diferente em execuções subsequentes de um sketch, use `randomSeed()` para inicializar o gerador de números aleatórios com uma entrada significantemente aleatória, como `analogRead()` em um pino desconectado.

Por outro lado, pode ser ocasionalmente útil usar sequências pseudoaleatórias exatamente repetidas. Isso pode ser conseguido chamando-se  `randomSeed()` com um número fixo, antes de começar a usar a sequência aleatória.

[%hardbreaks]

[float]
=== Parâmetros
`seed` - número para inicializar a sequência pseudoaleatória (long).

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo imprime números aleatórios na porta serial.

[source,arduino]
----
long randNumber;

void setup() {
  // inicializa a porta serial.
  Serial.begin(9600);

  // inicializa o gerador de números aleatórios.
  // um pino analógico desconectado irá retornar um
  // valor aleatório de tensão em analogRead()
  randomSeed(analogRead(0));
}

void loop() {
  // calcula o próximo número aleatório entre 0 e 299
  randNumber = random(300);

  // imprime o valor na porta serial
  Serial.println(randNumber);
  delay(50);
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
