---
title: random()
categories: [ "Functions" ]
subCategories: [ "Números Aleatórios" ]
---


= random()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
A função `random()` gera números pseudoaleatórios.
[%hardbreaks]


[float]
=== Sintaxe
`random(max)`
`random(min, max)`


[float]
=== Parâmetros
`min` - menor limite do valor aleatório, inclusivo e opcional  (long)

`max` - maior limite do valor aleatório, exclusivo (long)

[float]
=== Retorna
Um número inteiro aleatório entre min e max-1 (`long`) .

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo gera números aleatórios e os imprime na porta serial.

[source,arduino]
----
long randNumber;

void setup() {
  Serial.begin(9600);

  // Se o pino de entrada analógica 0 é deixado desconectado,
  // o ruído aleatório analógico irá causar a chamada de randomSeed()
  //  gerar sementes aleatórias diferentes cada vez que o sketch roda.
  // randomSeed() basicamente "embaralha" a função random().
  randomSeed(analogRead(0));
}

void loop() {
  // imprime um número aleatório entre 0 e 299
  randNumber = random(300);
  Serial.println(randNumber);

  // imprime um valor aleatório entre 10 e 19
  randNumber = random(10, 20);
  Serial.println(randNumber);

  delay(50);
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Se é importante que uma sequência de valores gerados por `random()` seja diferente em execuções subsequentes de um sketch, use `randomSeed()` para inicializar o gerador de números aleatórios com uma entrada significantemente aleatória, como `analogRead()` em um pino desconectado.

Por outro lado, pode ser ocasionalmente útil usar sequências pseudoaleatórias exatamente repetidas. Isso pode ser conseguido chamando-se  `randomSeed()` com um número fixo, antes de começar a usar a sequência aleatória.

O parâmetro `max` deve ser escolhido de acordo com o tipo de dado da variável na qual o valor será guardado. De qulquer forma, o valor máximo absoluto é limitado pela natureza `long` (32 bit - 2,147,483,647) do valor gerado. Escolher um valor `max` maior que isso não irá gerar erros durante a compilação, mas durante a execução do sketch, os números gerados irão se comportar de forma impredizível.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
