---
title: "compareTo()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---

= compareTo()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Compara duas Strings, testando se uma vem antes da outra na tabela ASCII, ou se são iguais. As Strings são comparadas caractere por caractere, usando os valores ASCII dos caracteres. Isso significa, por exemplo, que 'a' vem antes 'b', em ordem alfabética, mas depois de 'A' e 'B' etc. Números vem antes das letras.

[%hardbreaks]


[float]
=== Sintaxe
`minhaString.compareTo(minhaString2)`

[float]
=== Parâmetros
`minhaString`: uma variável do tipo String

`minhaString2`: outra variável do tipo String


[float]
=== Retorna
`um número negativo`: se minhaString vem antes de minhaString2

`0`: se minhaString é igual a minhaString2

`um número positivo`: se minhaString vem depois de minhaString2
--

// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
#EXEMPLO# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[Tutoriais String (Em Inglês)^] +
--
// SEE ALSO SECTION ENDS
