---
title: "substring()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---

= substring()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Retorna uma substring de uma String. O índice do início é inclusivo (o caractere correspondente é incluído na substring), mas o índice finalizador opcional é exclusivo (o caractere correspondente não é incluído na substring). Se o índice finalizador é omitido, a substring continua até o final da String.

[%hardbreaks]


[float]
=== Sintaxe
`minhaString.substring(inicio)` +
`minhaString.substring(inicio, fim)`
----

[float]
=== Parâmetros
`minhaString`: a variable of type String

`inicio`: o índice no qual começar a substring (inclusivo)

`fim` (optional): o índice no qual terminar a substring (exclusivo)


[float]
=== Retorna
A substring.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
#EXEMPLO# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[Tutoriais String (Em Inglês)^] +
--
// SEE ALSO SECTION ENDS
