---
title: Keyboard.press()
---

= Keyboard.press()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Quando chamada, `Keyboard.press()` funciona como se uma tecla fosse pressionada e segurada no seu teclado. Útil quando usando-se as link:../keyboardmodifiers[teclas modificadoras]. Pra liberar a tecla, use link:../keyboardrelease[Keyboard.release()] ou link:../keyboardreleaseall[Keyboard.releaseAll()].

É necessário chamar link:../keyboardbegin[Keyboard.begin()] antes de se usar `press()`.
[%hardbreaks]


[float]
=== Sintaxe
`Keyboard.press(char)`


[float]
=== Parâmetros
`char` : a tecla a ser pressionada

[float]
=== Retorna
`size_t` : o número de teclas pressionadas enviadas.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Keyboard.h>

// use essa opção para OSX:
// char ctrlKey = KEY_LEFT_GUI;
// use essa opção para Windows e Linux:
char ctrlKey = KEY_LEFT_CTRL;

void setup() {
  // Configura o pino 2 como entrada e ativa
  // o resistor pull-up tal que o pino seja HIGH
  // a menos que conectado ao ground:
  pinMode(2, INPUT_PULLUP);
  // inicializa o controle do teclado virtual:
  Keyboard.begin();
}

void loop() {
  while (digitalRead(2) == HIGH) {
    // não faz nada até que o pino 2 esteja LOW
    delay(500);
  }
  delay(1000);
  // novo documento:
  Keyboard.press(ctrlKey);
  Keyboard.press('n'); //equivalente ao atalho control + n
  delay(100);
  Keyboard.releaseAll();
  // espera uma nova janela abrir no computador:
  delay(1000);
----

--
// HOW TO USE SECTION ENDS
