---
title: Keyboard.print()
---

= Keyboard.print()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Envia uma tecla pressionada, ou uma sequência de teclas, para um computador conectado.

`Keyboard.print()` deve ser chamada após a inicialização com link:../keyboardbegin[Keyboard.begin()].
[%hardbreaks]


[float]
=== Sintaxe
`Keyboard.print(caractere)` +
`Keyboard.print(caracteres)`

[float]
=== Parâmetros
`caractere` : um char ou int a ser enviado ao computador como se fosse uma tecla pressionada no teclado. + 
`caracteres` : uma string a ser enviada ao computador como se fosse uma palavra ou frase digitada no teclado.

[float]
=== Retorna
`size_t` : número de bytes enviados.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Keyboard.h>

void setup() {
  // Configura o pino 2 como entrada e ativa
  // o resistor pull-up tal que o pino seja HIGH
  // a menos que conectado ao ground:
  pinMode(2, INPUT_PULLUP);
  // inicializa a emulação de um teclado USB
  Keyboard.begin();
}

void loop() {
  // se o botão for pressionado
  if(digitalRead(2)==LOW){
    // envia a mensagem
    Keyboard.print("Hello!");
  }
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
Quando você usa a função `Keyboard.print()`, o Arduino toma o controle do computador! Tenha certeza que você tem controle de quando as mensagens vão ser enviadas antes de usar essa função. Pode ser difícil gravar um novo código no Arduino se ele estiver digitando algo o tempo todo. Um botão para ativar/desativar o controle do teclado é bastante efetivo.

--
// HOW TO USE SECTION ENDS
