---
title: "<"
title_expanded: menor que
categories: [ "Structure" ]
subCategories: [ "Operadores de Comparação" ]
---

= < Menor que


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Compara a variável à esquerda com o valor ou variável à direita do operador. Retorna verdadeiro (`true`) quando o operando à esquerda é menor que o operando à direita. Por favor note que você pode comparar variáveis de tipos de dados diferentes, mas isso pode gerar resultados imprevisíveis. Por isso é recomendado comparar variáveis do mesmo tipo de dados incluindo o atributo signed/unsigned.

[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
x < y;  // é verdadeiro se x é menor que y e é falso se x é igual ou maior que y
----

[float]
=== Parâmetros
`x`: variável. *Tipos de dados permitidos:* int, float, double, byte, short, long +
`y`: variável ou constante. *Tipos de dados permitidos:* int, float, double, byte, short, long

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
if (x < y) {  // testa se x é menor que y
  // faz algo apenas se o resultado da comparação é verdadeiro
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Números positivos são maiores que números negativos.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




//SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
