---
title: delay()
categories: [ "Functions" ]
subCategories: [ "Funções Temporizadoras" ]
---

= delay()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Pausa o programa por uma quantidade especificada de tempo (em milissegundos). Cada segundo equivale a 1000 milissegundos.
[%hardbreaks]


[float]
=== Sintaxe
`delay(ms)`


[float]
=== Parâmetros
`ms`: o número de milissegundos para pausar o programa (`unsigned long`)

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código pausa o programa por um segundo antes de trocar o estado do pino 13.

[source,arduino]
----
int ledPin = 13;              // LED conectado ao pino digital 13

void setup() {
  pinMode(ledPin, OUTPUT);    // configura o pino digital como saída
}

void loop() {
  digitalWrite(ledPin, HIGH); // acende o LED
  delay(1000);                // espera por um segundo
  digitalWrite(ledPin, LOW);  // apaga o LED
  delay(1000);                // espera por um segundo
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Mesmo que seja fácil fazer um LED piscar usando a função `delay()`, e muitos sketches usam delays pequenos para tarefas como debouncing de botões, o uso de `delay()` em um sketch possui desvantagens significantes. Nenhuma leitura de sensores, cálculos matemáticos, ou manipulação de pinos podem ocorrer durante a função `delay()`, para resumir, causa a pausa de qualquer atividade. Para métodos alternativos de controlar temporizações, veja o sketch link:http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blink Sem Delay (Em Inglês)], que verifica a função link:../millis[millis()] até que o tempo suficiente tenha passado. Programadores mais habilidosos usualmente evitam o uso da função `delay()` para timing de eventos mais longos que dezenas de milissegundos, a menos que o sketch Arduino seja muito simples.

No entanto, certas coisas continuam a acontecer enquanto a função delay() está controlando o microcontrolador, porque a função delay não desativa interrupções. Comunicação serial recebida no pino RX é armazenada, valores PWM de (link:../../analog-io/analogwrite[analogWrite]) e estados dos pinos são mantidos, e link:../../external-interrupts/attachinterrupt[interrupções externas] irão funcionar como devem.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
* #EXEMPLO# http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blink Sem Delay (Em Inglês)^]

--
// SEE ALSO SECTION ENDS
