---
title: micros()
categories: [ "Functions" ]
subCategories: [ "Funções Temporizadoras" ]
---





= micros()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Retorna o número de microssegundos passados desde que a placa Arduino começou a executar o programa atual. Esse número irá sofrer overflow (chegar ao maior número possível e então voltar pra zero), após aproximadamente 70 minutos. Em placas Arduino 16 MHz (ex. UNO e Nano), essa função possui uma resolução de quatro microssegundos (isto é, o número retornado é sempre um múltiplo de quatro). Em placas Arduino 8 MHz (ex. LilyPad), essa função possui uma resolução de oito microssegundos.
[%hardbreaks]


[float]
=== Sintaxe
`time = micros()`


[float]
=== Parâmetros
Nenhum

[float]
=== Retorna
O número de microssegundos desde que o programa iniciou (unsigned long).

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo imprime o número de microssegundos passados desde que a placa Arduino foi ligada.
[source,arduino]
----
unsigned long time;

void setup() {
  Serial.begin(9600);
}
void loop() {
  Serial.print("Time: ");
  time = micros();

  Serial.println(time); // imprime o tempo desde que o programa iniciou
  delay(1000);          // espera um segundo, para não enviar quantidades massivas de dados
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Há 1000 (mil) microssegundos em um milissegundo e 1000000 (um milhão) de microssegundos em um segundo.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
