---
title: millis()
categories: [ "Functions" ]
subCategories: [ "Funções Temporizadoras" ]
---





= millis()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Retorna o número de milissegundos passados desde que a placa Arduino começou a executar o programa atual. Esse número irá sofrer overflow (chegar ao maior número possível e então voltar pra zero), após aproximadamente 50 dias.
[%hardbreaks]


[float]
=== Sintaxe
`time = millis()`


[float]
=== Parâmetros
Nenhum

[float]
=== Retorna
O número de milissegundos desde que o programa iniciou (unsigned long)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código lê o tempo em milissegundos desde que a placa Arduino foi ligada.

[source,arduino]
----
unsigned long time;

void setup() {
  Serial.begin(9600);
}
void loop() {
  Serial.print("Time: ");
  time = millis();

  Serial.println(time); // imprime o tempo desde que o programa iniciou
  delay(1000);          // espera um segundo, para não enviar quantidades massivas de dados
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Note que o valor retornado por `millis()` é unsigned long, erros podem ser gerados se o programador tentar fazer operações matemáticas com outros tipos de dados, como ints.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
* #EXEMPLO# http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blink Sem Delay (Em Inglês)^]

--
// SEE ALSO SECTION ENDS
