---
title: Stream.readBytes()
---

= readBytes()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`readBytes()` lê caracteres de uma stream para um buffer. A função termina se o número de bytes especificado foi lido, ou se ocorre time-out (ver  link:../streamsettimeout[setTimeout()]).

`readBytes()` retorna o número de bytes colocados no buffer. Um valor 0 indica que não foram encontrados dados válidos.

Essa função é parte da classe Stream, e pode ser chamada por qualquer classe que herda da mesma (Wire, Serial, etc). Veja a página principal da link:../../stream[classe Stream] para mais informações.
[%hardbreaks]


[float]
=== Sintaxe
`stream.readBytes(buffer, length)`


[float]
=== Parâmetros
`stream` : uma instância de uma classe que herda da classe Stream.

`buffer` : o buffer para se guardar os bytes (`char[]` ou `byte[]`)

`length` : o número de bytes a serem lidos `read(int)`

[float]
=== Retorna
O número de bytes colocados no buffer (`size_t`)

--
// OVERVIEW SECTION ENDS
