---
title: Stream.parseInt()
---

= parseInt()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`parseInt()` retorna o primeiro número inteiro (long) válido da stream. Caracteres iniciais que não são dígitos (ou o sinal de menos) são ignorados.

Em particular:

* Caracteres iniciais que não são dígitos ou um sinal de menos, são ignorados; +
* O parsing para qaundoo nenhum caractere tem sido lido em um time-out de valor confgurável, ou um caractere não-dígito é lido; +
* Se nehum digito válido foi lido quando ocorre time-out (ver link:../streamsettimeout[Stream.setTimeout()]), é retornado 0;

Essa função é parte da classe Stream, e é chamada por qualquer classe que herda da mesma (Wire, Serial, etc). Veja a página principal da link:../../stream[classe Stream] para mais informações.
[%hardbreaks]


[float]
=== Sintaxe
`stream.parseInt(list)`

`stream.parseInt(''list', char skipchar')`

[float]
=== Parâmetros
`stream` : uma instância de uma classe que herda da classe Stream.

`list` : a stream a se checar por ints (`char`)

`skipChar`: usado para ignorar o carctere indicado na busca. Usado, por exemplo, para ignorar o ponto em "2.000.000".

[float]
=== Retorna
`long`

--
// OVERVIEW SECTION ENDS
