---
title: Stream.setTimeout()
---




= setTimeout()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`setTimeout()` configura o número máximo de milissegundos a se esperar por dados. O valor padrão é de 1000 milisegundos.

Essa função é parte da classe Stream, e é chamada por qualquer classe que herda da mesma (Wire, Serial, etc). Veja a página principal da link:../../stream[classe Stream] para mais informações.
[%hardbreaks]

[float]
=== Sintaxe
`stream.setTimeout(time)`


[float]
=== Parâmetros
`stream` : uma instância de uma classe que herda da classe Stream.

`time` : duração do timeout em milissegundos (`long`).

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas e Advertências
Funções da classe Stream que usam o valor de tempo limite configurado via `setTimeout()`:

* `find()`
* `findUntil()`
* `parseInt()`
* `parseFloat()`
* `readBytes()`
* `readBytesUntil()`
* `readString()`
* `readStringUntil()`

[%hardbreaks]

--
// HOW TO USE SECTION ENDS
