---
title: Stream.parseInt()
---




= parseInt()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`parseInt()` returns the first valid (long) integer number from the current position. Initial characters that are not integers (or the minus sign) are skipped.

In particular:

* Initial characters that are not digits or a minus sign, are skipped; +
* Parsing stops when no characters have been read for a configurable time-out value, or a non-digit is read; +
* If no valid digits were read when the time-out (see link:../streamsettimeout[Stream.setTimeout()]) occurs, 0 is returned;

Essa função é parte da classe Stream, e é chamada por qualquer classe que herda da mesma (Wire, Serial, etc). Veja a página principal da link:../../stream[classe Stream] para mais informações.
[%hardbreaks]


[float]
=== Sintaxe
`stream.parseInt(list)`

`stream.parseInt(''list', char skipchar')`

[float]
=== Parâmetros
`stream` : uma instância de uma classe que herda da classe Stream.

`list` : the stream to check for ints (`char`)

`skipChar`: used to skip the indicated char in the search. Used for example to skip thousands divider.

[float]
=== Retorna
`long`

--
// OVERVIEW SECTION ENDS
