---
title: Stream.readBytesUntil()
---

= readBytesUntil()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`readBytesUntil()` lê bytes de uma stream para um buffer. A função termina se o carctere terminador é encontrado, o número de bytes determinado foi lido, ou ocorre time-out (ver link:../streamsettimeout[setTimeout()]). A função retorna o caractere até o último caractere antes o terminador fornecido. O terminador em si não é retornado no buffer.

`readBytesUntil()` retorna o número de bytes colocados no buffer. Um valor 0 indica que não foram encontrados dados válidos.

Essa função é parte da classe Stream, e pode ser chamada por qualquer classe que herda da mesma (Wire, Serial, etc). Veja a página principal da link:../../stream[classe Stream] para mais informações.
[%hardbreaks]


[float]
=== Sintaxe
`stream.readBytesUntil(character, buffer, length)`


[float]
=== Parâmetros
`stream` : uma instância de uma classe que herda da classe Stream.

`character` : o caractere para encerra a busca (`char`)

`buffer`: o buffer para armazenar os bytes (`char[]` ou `byte[]`)

`length` : o número de bytes a serem lidos (int)

[float]
=== Retorna
O número de bytes colocados no buffer.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas e Advertências
O caractere terminador é descartado do buffer serial.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
