---
title: Stream.readStringUntil()
---


= readStringUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`readStringUntil()` lê caracteres de uma stream para uma String. A função termina se o caractere terminador é detectado ou se ocorre time-out (ver link:../streamsettimeout[setTimeout()]).

Essa função é parte da classe Stream, e pode ser chamada por qualquer classe que herda da mesma (Wire, Serial, etc). Veja a página principal da link:../../stream[classe Stream] para mais informações.
[%hardbreaks]


[float]
=== Sintaxe
`stream.readString(terminator)`


[float]
=== Parâmetros
`stream` : uma instância de uma classe que herda da classe Stream.

`terminator` : o caractere para encerrar a busca (`char`)

[float]
=== Retorna
A String completa da Stream, até o caractere terminador.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notes and Warnings
The terminator character is discarded from the stream.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
