---
title: Stream.readBytesUntil()
---




= readBytesUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`readBytesUntil()` reads characters from a stream into a buffer. The function terminates if the terminator character is detected, the determined length has been read, or it times out (see link:../streamsettimeout[setTimeout()]).

`readBytesUntil()` returns the number of bytes placed in the buffer. A 0 means no valid data was found.

Essa função é parte da classe Stream, e é chamada por qualquer classe que herda da mesma (Wire, Serial, etc). Veja a página principal da link:../../stream[classe Stream] para mais informações.
[%hardbreaks]


[float]
=== Sintaxe
`stream.readBytesUntil(character, buffer, length)`


[float]
=== Parâmetros
`stream` : uma instância de uma classe que herda da classe Stream.

`character` : the character to search for (`char`)

`buffer`: the buffer to store the bytes in (`char[]` or `byte[]`)

`length : the number of bytes to `read(int)`

[float]
=== Retorna
The number of bytes placed in the buffer.

--
// OVERVIEW SECTION ENDS
