---
title: "/* */"
title_expanded: block comment
categories: [ "Structure" ]
subCategories: [ "Outros Elementos da Sintaxe" ]
---

= /* */ Comentário de bloco


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
*Comentários* são textos no programa que são usadas para informar você e a outros a forma como o programa funciona. Eles são ignorados pelo compilador, e não fazem parte do arquivo gravado no chip, então não ocupam nenhum espaço na memória flash do microcontrolador. O  propósito dos comentários lhe ajudar a entender (ou lembrar) como funcionam partes do seu código, ou informar a outros também como o seu programa funciona.
[%hardbreaks]

O começo de um *comentário em bloco* ou *comentário de múltiplas linhas* é marcado pelo símbolo `/\*` e o símbolo `*/` marca o seu final. Esse tipo de comentário é chamado assim pois pode se estender por mais de uma linha; um vez que o compilador encontre o símbolo `/\*`, ele ignora o texto seguinte até encontrar um `*/`.

// NOTE TO THE EDITOR: The '\' before the '*' in certain places are to escape the '*' from making the text bolder.
// In places were '\' is not used before '*', it is not actually required.
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
[source,arduino]
----
/* Esse é um comentário válido */

/*
  Blink
  Acende um LED por um segundo, depois apaga por um segundo, repetidamente.

  Esse código encontra-se um domínio público.
  (outro comentário válido)
*/

/*
  if (gwb == 0){   // Comentários de única linha não permitidos dentro de um comentário em bloco 
  x = 3;           /* Mas outro comentário de múltiplas linhas, não. Esse comentário é inválido */
  }
// Não esqueça o símbolo para "fechar" o comentário - deve estar balanceado!
*/
----
[%hardbreaks]

[float]
=== Notas e Advertências
Quando experimentar com código, "comentar" partes de seu programa é uma forma conveniente de remover partes problemáticas do seu código tempoariamente. Isso mantém as linhas de código, mas as transforma em comentários, se forma que o compilador apenas as ignora. Isso pode ser útil quando você estiver procurando um problema, ou quando um programa se recusa a compilar e o erro de compilação é enigmático ou inútil.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também
[role="language"]

--
// SEE ALSO SECTION ENDS
