---
title: "{}"
title_expanded: chaves
categories: [ "Structure" ]
subCategories: [ "Outros Elementos da Sintaxe" ]
---

= {} Chaves


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
As chaves são uma característica importante da linguagem C. Elas são usadas em diversas estruturas diferentes, mostradas abaixo, e isso pode as vezes ser confuso para iniciantes. +
Uma chave `{` deve ser sempre fechada por outra chave `}`. Essa é uma condição que é frequentemente chamada de as chaves estarem balanceadas. A IDE Arduino inclui uma forma conveniente de checar o balanço de duas chaves. Apenas escolha uma chave, ou até mesmo clique no ponto de inserção imediatamente após a chave, se a outra chave do par será destacada.
[%hardbreaks]
//// Beginners programmers, and programmers coming to C from the BASIC language often find using braces confusing or daunting. After all, the same curly braces replace the RETURN statement in a subroutine (function), the ENDIF statement in a conditional and the NEXT statement in a FOR loop.
[%hardbreaks]
////
Chaves desbalanceadas podem frequentemente resultar em erros enigmáticos, que podem as vezes ser difíceis de se encontrar em um programa longo. Por causa de seu uso variado, as chaves são incrivelmente importantes para o programa e mover uma chave pode afetar dramaticamente o funcionamento de um programa.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
Os usos principais das chaves são listados nos exemplos abaixo.


[float]
==== Funções

[source,arduino]
----
void minhafuncao(tipo argumento){
  comando(s)
}
----
[%hardbreaks]


[float]
==== Loops

[source,arduino]
----
while (expressão boolena)
{
 comando(s)
}

do
{
 comando(s)
} while (expressão boolena);

for (inicialização; condição; incremento)
{
 comando(s)
}
----
[%hardbreaks]




[float]
==== Estruturas Condicionais

[source,arduino]
----
if (expressão boolena)
{
 comandos(s)
}

else if (expressão boolena)
{
 comandos(s)
}
else
{
 comandos(s)
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também
[role="language"]

--
// SEE ALSO SECTION ENDS
