---
title: "#define"
title_expanded: define
categories: [ "Structure" ]
subCategories: [ "Outros Elementos da Sintaxe" ]
---

= #define

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`#define` é uma diretiva muito útil da linguagem C++ que  permite ao programador dar um nome a um valor constante antes de o programa ser compilado. Constantes definidas no arduino não ocupam nenhum espaço na memória de programa do chip. O compilador irá substituir referências a essas constantes pelo valor definido no tempo de compilação.
[%hardbreaks]

Isso pode ter alguns efeitos colaterais desagradáveis no entanto, por exemplo, se o nome de uma constante que foi definida com #defined é incluído em outra constante ou nome de uma variável. Nesse caso o texto seria trocado pelo número  (ou texto) definido com #define.
[%hardbreaks]

Em geral, a palavra-chave link:../../../variables/variable-scope\--qualifiers/const[const] é recomendada para se definir constantes e deveria ser usada em vez de #define.
[%hardbreaks]

[float]
=== Sintaxe
[source,arduino]
----
#define nomeDaConstante valor
----
Note que o # é necessário.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
#define pinoLED 3
// O compilador irá substituir qualquer menção de pinoLED com o valor 3 no tempo de compilação.
----
[%hardbreaks]

[float]
=== Notas e Advertências
Não há ponto e vírgula após a diretiva #define. Se você incluir uma, o compilador irá acusar erros.

[source,arduino]
----
#define pinoLED 3;    // isso é inválido
----

Similarmente, incluir sinal de igual após #define também resultará em erros

[source,arduino]
----
#define pinoLED  = 3  // também é inválido
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM#	link:../../../variables/variable-scope\--qualifiers/const[palavra-chave const] +
#LINGUAGEM#	link:../../../variables/constants/constants[Constantes]

--
// SEE ALSO SECTION ENDS
