---
title: "#include"
title_expanded: include
categories: [ "Structure" ]
subCategories: [ "Outros Elementos da Sintaxe" ]
---

= #include


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
A diretiva `#include` é usada para incluir bibliotecas externas ao seu sketch. Isso dá acesso a um grande número de bibliotecas padrão da linguagem C (grupos de funções prontas), e também bibliotecas escritas especialmente para a linguagem Arduino.
[%hardbreaks]

A referência principal para bibliotecas C AVR C (AVR é a referência dos chips Microchip (previamente Atmel) utilizados em muitas placas Arduino) pode ser encontrada http://www.nongnu.org/avr-libc/user-manual/modules.html[aqui^].
[%hardbreaks]

Note que `#include`, similarmente a link:../define[`#define`], não é terminada com um ponto e vírgula, e o compilador irá mostrar  mensagens de erro enigmáticas se você adicionar um.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
Esse exemplo inclui uma biblioteca que é usada para colocar dados no espaço de programa (memória _flash_) em vez da _ram_. Isso salva  espaço da ram para necessidades dinâmicas e faz tabelas de consulta (lookup tables) mais práticas.


[source,arduino]
----
#include <avr/pgmspace.h>

prog_uint16_t myConstants[] PROGMEM = {0, 21140, 702  , 9128,  0, 25764, 8456,
0,0,0,0,0,0,0,0,29810,8968,29762,29762,4500};
----


--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]


--
// SEE ALSO SECTION ENDS
