---
title: "#include"
title_expanded: include
categories: [ "Structure" ]
subCategories: [ "Outros Elementos da Sintaxe" ]
---

= #include


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
A diretiva `#include` é usada para incluir bibliotecas externas ao seu sketch. Isso dá acesso a um grande número de bibliotecas padrão da linguagem C (grupos de funções prontas), e também bibliotecas escritas especialmente para a linguagem Arduino.
[%hardbreaks]

A referência principal para bibliotecas C AVR C (AVR é a referência dos chips Microchip (previamente Atmel) utilizados em muitas placas Arduino) pode ser encontrada http://www.nongnu.org/avr-libc/user-manual/modules.html[aqui^].
[%hardbreaks]

Note que `#include`, similarmente a link:../define[`#define`], não é terminada com um ponto e vírgula, e o compilador irá mostrar  mensagens de erro enigmáticas se você adicionar um.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
Esse exemplo inclui a bilbioteca Servo para que suas funções possam ser usadas para controlar um servomotor.


[source,arduino]
----
#include <Servo.h>

Servo meuservo;  // cria um objeto do tipo Servo para controlar um servomotor

void setup() {
  meuservo.attach(9);  // associa o motor no pino 9 ao objeto meuservo
}

void loop() {
  for (int pos = 0; pos <= 180; pos += 1) { // vai de 0 graus a 180 graus
    // em passos de 1 grau
    meuservo.write(pos);             // diz ao servo para ir para a posição na variável 'pos'
    delay(15);                       // espera 15ms para que o servo chegue a posição
  }
  for (int pos = 180; pos >= 0; pos -= 1) { // // vai de 180 graus a 0 graus
    meuservo.write(pos);             // diz ao servo para ir para a posição na variável 'pos'
    delay(15);                       // espera 15ms para que o servo chegue a posição
  }
}
----


--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]


--
// SEE ALSO SECTION ENDS
