---
title: "//"
title_expanded: comentário
categories: [ "Structure" ]
subCategories: [ "Outros Elementos da Sintaxe" ]
---

= // Comentário de única linha

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
*Comentários* são textos no programa que são usadas para informar você e a outros a forma como o programa funciona. Eles são ignorados pelo compilador, e não fazem parte do arquivo gravado no chip, então não ocupam nenhum espaço na memória flash do microcontrolador. O propósito dos comentários é lhe ajudar a entender (ou lembrar) como funcionam partes do seu código, ou informar a outros também como o seu programa funciona.
[%hardbreaks]

Um *comentário de uma só linha* começa com `//` (duas barras adjacentes). Esse tipo de comentário termina automaticamente no final da linha. O que quer que seja que estiver após `//` até o final da linha será ignorado pelo compilador.
--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
Há duas formas diferentes de se usar um comentário de uma só linha:

[source,arduino]
----
// O pino 13 tem um LED conectado na maioria das placas Arduino.
// Dá um nome para esse LED:
int led = 13;


digitalWrite(led, HIGH);  // acendo o LED (HIGH é o nível da tensão)
----
[%hardbreaks]

[float]
=== Notas e Advertências
Quando experimentar com código, "comentar" partes de seu programa é uma forma conveniente de remover partes problemáticas do seu código temporariamente. Isso mantém as linhas de código, mas as transforma em comentários, se forma que o compilador apenas as ignora. Isso pode ser útil quando você estiver procurando um problema, ou quando um programa se recusa a compilar e o erro de compilação é enigmático ou inútil.
[%hardbreaks]


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
