---
title: "^"
title_expanded: OU EXCLUSIVO
categories: [ "Structure" ]
subCategories: [ "Operadores Bitwise" ]
---

= ^ XOR Bitwise


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Na linguagem C++ existe um operador um pouco incomum chamado de OU EXCLUSIVO, também conhecido como XOR (Em Inglês é pronunciado "eks-or"), bit-a-bit. O operador XOR bitwise é escrito usando-se o símbolo `^`. Uma operação XOR bit-a-bit resulta em 1 apenas se os bits de entrada são diferentes. Se iguais, o resultado é zero.
[%hardbreaks]

Precisamente,

    0  0  1  1    operando1
    0  1  0  1    operando2
    ----------
    0  1  1  0    (operando1 ^ operando2) - resultado retornado
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
int x = 12;     // binário: 1100
int y = 10;     // binário: 1010
int z = x ^ y;  // binário: 0110, ou decimal 6
----
[%hardbreaks]

O operador ^ é frequentemente utilizado para trocar (isto é, mudar de 0 para 1, ou 1 para 0) alguns dos bits em uma expressão inteira. Em uma operação XOR se há um 1 no bit da máscara, aquele bit é invertido; se há um 0, o bit não é invertido e continua o mesmo. Abaixo um programa para piscar um LED no pino digital 5.

[source,arduino]
----
// Blink_Pin_5
// Demo do XOR
void setup() {
  DDRD = DDRD | B00100000;  // configura o pino digital 5 como saída
  Serial.begin(9600);
}

void loop() {
  PORTD = PORTD ^ B00100000;  // inverte bit 5 (pino 5), e deixa os outros intocados
  delay(100);
}
----


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
#EXEMPLO# https://www.arduino.cc/playground/Code/BitMath[Tutorial BitMath (Em Inglês)^]

--
// SEE ALSO SECTION ENDS
