---
title: "+"
title_expanded: "adição"
categories: [ "Structure" ]
subCategories: [ "Operadores Aritméticos" ]
---

= + Adição

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
*Adição* é uma das quatro operações ariméticas fundamentais. O operador `+` (mais) opera em dois operandos para produzir a soma dos mesmos.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
soma = operando1 + operando2;
----

[float]
=== Parâmetros
`soma` : variável. *Tipos de dados permitidos:* int, float, double, byte, short, long +
`operando1` : variável ou constante. *Tipos de dados permitidos:* int, float, double, byte, short, long +
`operando2` : variável ou constante. *Tipos de dados permitidos:* int, float, double, byte, short, long
[%hardbreaks]
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
int a = 5, b = 10, c = 0;
c = a + b; // A variável 'c' recebe o valor 15 depois que essa operação é executada
----
[%hardbreaks]

[float]
=== Notas e Advertências
1. O operação de adição pode causar overflow se o resultado é maior que o que pode ser armazenado no tipo de dado (ex. adicionar 1 a um inteiro com valor 32,767 resulta em -32,768).

2. Se um dos números (operandos) é do tipo float ou double, a matemática de ponto flutuante será usada no cálculo.

3. Se os operandos são do tipo de dado float ou double e a variável que armazena a soma é int, então apenas a parte inteira é salva no resultado e e a parte racional é perdida.

[source,arduino]
----
float a = 5.5, b = 6.6;
int c = 0;
c = a + b; // a variável 'c' guarda o valor 12 apenas, em vez de 12.1 
----
[%hardbreaks]
--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
