---
title: "="
title_expanded: "operador de atribuição"
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---

= = Atribuição (único sinal de igual)

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
O sinal de igual `=` na linguagem de programação C++ é chamado operador de atribuição. Seu significado é diferente das aulas de matemática, onde ele indica uma equação ou igualdade. O operador de atribuição indica ao microcontrolador que compute qualquer valor ou expressão que estiver à direita do sinal de igual, e o armazene na variável à esquerda do sinal de igual.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
int sensVal;              // declara uma variável inteira chamada sensVal
sensVal = analogRead(0);  // armazena a tensão (digitalizada) do pino analógico 0 em SensVal
----
[%hardbreaks]

[float]
=== Notas e Advertências
1. A variável à esquerda do operador de atribuição ( sinal = ) precisa ser um tipo de dado capaz de armazenar o resultado da operação. Se ela não for grande o suficiente para guardar o valor, o resultado armazenado será incorreto. Veja os tipos de dados da linguagem Arduino para mais informações sobre seu tamanho.

2. Não confunda o operador de atribuição [ = ] (sinal de igual único) com o operador de comparação [ == ] (sinal de igual duplo), o qual avalia se se duas expressões são iguais.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM#  link:../../control-structure/if[if (operadores condicionais)] +
#LINGUAGEM#  link:../../../variables/data-types/char[char] +
#LINGUAGEM#  link:../../../variables/data-types/int[int] +
#LINGUAGEM#  link:../../../variables/data-types/long[long] +

--
// SEE ALSO SECTION ENDS
