---
title: "/"
title_expanded: "divisão"
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---

= / Divisão

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
*Divisão* é uma das quatro operações aritméticas fundamentais. O operador `/` (barra) opera em dois operandos para produzir o resultado.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
resultado = numerador / denominador;
----

[float]
=== Parâmetros
`resultado` : variável. *Tipos de dados permitidos:* int, float, double, byte, short, long  +
`numerador` : variável ou constante. *Tipos de dados permitidos:* int, float, double, byte, short, long  +
`denominador` : variável ou constante *diferente de zero*. *Tipos de dados permitidos:* int, float, double, byte, short, long
[%hardbreaks]

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
int a = 50;
int b = 10;
int c = 0;
c = a / b;  // A variável 'c' recebe o valor 5 depois que essa operação é executada
----
[%hardbreaks]

[float]
=== Notas e Advertências
1. Se um dos números (operandos) é do tipo float ou double, a matemática de ponto flutuante será usada no cálculo.

2. Se os operandos são do tipo de dado float ou double e a variável que armazena a divisão é int, então apenas a parte inteira é salva no resultado e a parte racional é perdida.

[source,arduino]
----
float a = 55.5;
float b = 6.6;
int c = 0;
c = a / b;  // a variável 'c' armazena o valor 8 em vez do resultado esperado 8.409
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
