---
title: "%"
title_expanded: "resto"
categories: [ "Structure" ]
subCategories: [ "Operadores Aritméticos" ]
---

= % Módulo

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
A operação *resto* calcula o resto da divisão de um inteiro por outro. Esse operador também pode ser chamado de módulo. Apesar do nome, não confunda o operador módulo (%) da computação com o módulo da matemática ( |x| ), que na linguagem arduino é calculado através da função `abs()`. Esse operador é útil para manter uma variável dentro de um intervalo (ex. o tamanho de um vetor). O símbolo `%` (porcentagem) é usado para realizar a operação resto.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
resto = dividendo % divisor;
----

[float]
=== Parâmetros
`resto` : variável. *Tipos de dados permitidos:* int, float, double +
`dividendo` : variável ou constante. *Tipos de dados permitidos:* int +
`divisor` : variável ou constante *diferente de zero*. *Tipos de dados permitidos:* int
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
int x = 0;
x = 7 % 5;    // x agora contém 2
x = 9 % 5;    // x agora contém 4
x = 5 % 5;    // x agora contém 0
x = 4 % 5;    // x agora contém 4
----

[source,arduino]
----
/* Atualiza um valor do vetor a cada vez em um loop */

int values[10];
int i = 0;

void setup() {}

void loop()
{
  values[i] = analogRead(0);
  i = (i + 1) % 10;   // o operador módulo faz a variável i "rolar" pro próximo valor
}
----
[%hardbreaks]

[float]
=== Notas e Advertências

O operador resto não funciona em floats.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
