---
title: "*"
title_expanded: "multiplicação"
categories: [ "Structure" ]
subCategories: [ "Operadores Aritméticos" ]
---

= * Multiplicação


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
*Multiplicação* é uma das quatro operações aritméticas fundamentais. O operador `*` (asterisco) opera em dois operandos para produzir o produto.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
produto = operando1 * operando2;
----

[float]
=== Parâmetros
`produto` : variável. *Tipos de dados permitidos:* int, float, double, byte, short, long  +
`operando1` : variável ou constante. *Tipos de dados permitidos:* int, float, double, byte, short, long  +
`operando2` : variável ou constante. *Tipos de dados permitidos:* int, float, double, byte, short, long
[%hardbreaks]

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
int a = 5;
int b = 10;
int c = 0;
c = a * b;  // A variável 'c' recebe o valor 50 depois que essa operação é executada
----
[%hardbreaks]

[float]
=== Notas e Advertências
1. O operação de multiplicação pode causar overflow se o resultado é maior que o que pode ser armazenado no tipo de dado.

2. Se um dos números (operandos) é do tipo float ou double, a matemática de ponto flutuante será usada no cálculo.

3. Se os operandos são do tipo de dado float ou double e a variável que armazena o produto é int, então apenas a parte inteira é salva no resultado e a parte racional é perdida.

[source,arduino]
----
float a = 5.5;
float b = 6.6;
int c = 0;
c = a * b;  // a variável 'c' armazena o valor 36 em vez do resultado esperado 36.3
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
