---
title: "-"
title_expanded: "subtração"
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---


= - Subtração


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
*Subtração* é uma das quatro operações aritméticas fundamentais. O operador `-` (menos) opera em dois operanddos para produzir a diferença do segundo pelo primeiro.
[%hardbreaks]


[float]
=== Sintaxe
[source,arduino]
----
diferença = operando1 - operando2;
----

[float]
=== Parâmetros
`diferença` : variável. *Tipos de dados permitidos:* int, float, double, byte, short, long +
`operando1` : variável ou constante. *Tipos de dados permitidos:* int, float, double, byte, short, long +
`operando2` : variável ou constante. *Tipos de dados permitidos:* int, float, double, byte, short, long
[%hardbreaks]

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo

[source,arduino]
----
int a = 5, b = 10, c = 0;
c = a - b; // A variável 'c' recebe o valor -5 depois que essa operação é executada
----
[%hardbreaks]

[float]
=== Notas e Advertências
1. O operação de subtração pode causar overflow se o resultado é menor que o que pode ser armazenado no tipo de dado (ex. subtrair 1 de um `int` com valor -32,768 resulta em 32,767).

2. Se um dos números (operandos) é do tipo float ou double, a matemática de ponto flutuante será usada no cálculo.

3. Se os operandos são do tipo de dado float ou double e a variável que armazena a diferença é int, então apenas a parte inteira é salva no resultado e a parte racional é perdida.

[source,arduino]
----
float a = 5.5, b = 6.6;
int c = 0;
c = a - b; // a variável 'c' armazena o valor -1 em vez do resultado esperado -1.1
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="language"]

--
// SEE ALSO SECTION ENDS
