---
title: Serial
categories: [ "Functions" ]
subCategories: [ "Comunicação" ]
---

= Serial()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Usada para comunicação entre uma placa Arduino e um computador ou outros dispositivos. Todas as placas Arduino possuem pelo menos uma porta serial (também conhecida como UART ou USART), chamada `Serial`. Ela comunica-se nos pinos digitais 0 (RX) e 1 (TX) como também com um computador via USB. Logo, se você usar essas funções, você não pode usar ao mesmo tempo os pinos 0 e 1 como entradas ou saídas digitais.
[%hardbreaks]
Você pode usar o monitor serial presente na IDE do Arduino para se comunicar com uma placa Arduino. Clique no botão do monitor serial na barra de ferramentas e escolha e usar a mesma taxa de transferência (baud rate) usada na chamada de `begin()`.
[%hardbreaks]
Comunicação serial nos pinos TX/RX usa níveis lógicos TTL (5V ou 3.3V dependendo da placa). *Não conecte esses pinos diretamente um uma porta serial RS232; esses operam em +/- 12V e podem danificar sua placa Arduino.*
[%hardbreaks]
O *Arduino Mega* tem três portas seriais adicionais: `Serial1` nos pinos 19 (RX) e 18 (TX), `Serial2` nos pinos 17 (RX) e 16 (TX), `Serial3` nos pinos 15 (RX) e 14 (TX). Para usar esses pinos para comunicar com seu computador pessoal, você vai precisar de um adaptador USB-serial extra, pois esses pinos não são conectados ao adaptador USB-serial do Arduino Mega. para usá-los para comunicar com um dispositivo serial TTL externo, conecte o pino TX do Arduino ao pino RX do dispositivo, o pino RX ao pino TX do dispositivo, e o ground de seu Mega ao ground do dispositivo.
[%hardbreaks]
O *Arduino DUE* tem três portas seriais TTL de 3.3V adicionais: `Serial1` nos pinos 19 (RX) e 18 (TX); `Serial2` nos pinos 17 (RX) e 16 (TX), `Serial3` nos pinos 15 (RX) e 14 (TX). Pinos 0 e 1 são também conectados aos pinos correspondentes do chip serial ATmega16U2, o qual é conectado a porta debug USB. Adicionalmente, há uma porta USB-serial nativa no chip SAM3X, `SerialUSB`.
[%hardbreaks]
A placa *Arduino Leonardo* usa `Serial1` para comunicar-se via serial TTL (5V) nos pinos 0 (RX) e 1 (TX). `Serial` é reservada para comunicação USB CDC. Para mais informações, consulte as páginas getting started e hardware para o Leonardo .

--
// OVERVIEW SECTION ENDS


// FUNCTIONS SECTION STARTS
[#functions]
--

'''

[float]
=== Funções
link:../serial/ifserial[If(Serial)] +
link:../serial/available[available()] +
link:../serial/availableforwrite[availableForWrite()] +
link:../serial/begin[begin()] +
link:../serial/end[end()] +
link:../serial/find[find()] +
link:../serial/finduntil[findUntil()] +
link:../serial/flush[flush()] +
link:../serial/parsefloat[parseFloat()] +
link:../serial/parseint[parseInt()] +
link:../serial/peek[peek()] +
link:../serial/print[print()] +
link:../serial/println[println()] +
link:../serial/read[read()] +
link:../serial/readbytes[readBytes()] +
link:../serial/readbytesuntil[readBytesUntil()] +
link:../serial/settimeout[setTimeout()] +
link:../serial/write[write()] +
link:../serial/serialevent[serialEvent()]

'''

--
// FUNCTIONS SECTION ENDS


// SEEALSO SECTION STARTS
[#see_also]
--

[float]
=== Ver Também

[role="example"]

Exemplos (Em Inglês):

* #EXEMPLO# https://www.arduino.cc/en/Tutorial/ReadAsciiString[ReadAsciiString^]
* #EXEMPLO# https://www.arduino.cc/en/Tutorial/ASCIITable[ASCII TAble^]
* #EXEMPLO# https://www.arduino.cc/en/Tutorial/Dimmer[Dimmer^]
* #EXEMPLO# https://www.arduino.cc/en/Tutorial/Graph[Graph^]
* #EXEMPLO# https://www.arduino.cc/en/Tutorial/PhysicalPixel[Physical Pixel^]
* #EXEMPLO# https://www.arduino.cc/en/Tutorial/SerialCallResponse[Serial Call Response^]
* #EXEMPLO# https://www.arduino.cc/en/Tutorial/SerialCallResponseASCII[Serial Call Response ASCII^]


--
// SEEALSO SECTION ENDS
