---
title: Serial.available()
---

= available()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Retorna o número de bytes (caracteres) disponíveis para leitura da porta serial. Esses são dados que já chegaram e foram guardados no buffer de recebimento (o qual armazena 64 bytes). 

A função `Serial.available()` é herdada da classe link:../../stream[Stream].
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.available()`

[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

[float]
=== Retorna
O número de bytes disponíveis para leitura.
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo devolve um caractere recebido na porta serial.

[source,arduino]
----
int incomingByte = 0; // para  dados recebidos na porta serial

void setup() {
  Serial.begin(9600); // abre a porta serial, taxa de transmissão 9600 bps
}

void loop() {

  // enviar resposta apenas quando receber dados:
  if (Serial.available() > 0) {
    // lê o dado recebido:
    incomingByte = Serial.read();

    // responder o que foi recebido:
    Serial.print("Eu recebi: ");
    Serial.println(incomingByte, DEC);
  }
}
----
[%hardbreaks]

O código abaixo transfere os dados de uma porta serial do Arduino Mega para outra. Isso pode ser usado para conectar um dispositivo serial ao computador através da placa Arduino.

*Exemplo para o Arduino Mega:*
[source,arduino]
----
void setup() {
  Serial.begin(9600);
  Serial1.begin(9600);
}

void loop() {
  // Lê da porta 0, envia para porta 1:
  if (Serial.available()) {
    int inByte = Serial.read();
    Serial1.print(inByte, DEC);
  }
  // Lê da porta 1, envia para porta 0:
  if (Serial1.available()) {
    int inByte = Serial1.read();
    Serial.print(inByte, DEC);
  }
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver também

[role="language"]
#LINGUAGEM# link:../begin[begin()] +
#LINGUAGEM# link:../end[end()] +
#LINGUAGEM# link:../read[read()] +
#LINGUAGEM# link:../peek[peek()] +
#LINGUAGEM# link:../flush[flush()] +
#LINGUAGEM# link:../print[print()] +
#LINGUAGEM# link:../println[println()] +
#LINGUAGEM# link:../write[write()] +
#LINGUAGEM# link:../serialevent[SerialEvent()] +
#LINGUAGEM# link:../../stream/streamavailable[Stream.available()]

--
// SEE ALSO SECTION ENDS
