---
title: Serial.begin()
---

= begin()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Configura a taxa de transferência em bits por segundo (baud rate) para transmissão serial. Para comunicação com um computador, através do Monitor Serial da IDE, use uma das taxas listadas no canto inferior direito de sua janela. Você pode, no entanto, especificar outras taxas - por examplo, para comunicar nos pinos 0 e 1 com um componente que requer uma taxa de transferência peculiar.

Um segundo argumento opcional configura o número de bits no dado, paridade, e bits de parada (stop bits). Caso esse argumento não seja especificado, o padrão é 8 bits de dados, sem paridade e um stop bit.
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.begin(speed)`
`_Serial_.begin(speed, config)`

[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

`speed`: a taxa de transmissão em bits per second (baud rate) - (long)

`config`: configuração do número de bits por transmissão, paridade, e stop bits. Opções válidas são:

`SERIAL_5N1` +
`SERIAL_6N1` +
`SERIAL_7N1` +
`SERIAL_8N1` (o padrão) +
`SERIAL_5N2` +
`SERIAL_6N2` +
`SERIAL_7N2` +
`SERIAL_8N2` +
`SERIAL_5E1` +
`SERIAL_6E1` +
`SERIAL_7E1` +
`SERIAL_8E1` +
`SERIAL_5E2` +
`SERIAL_6E2` +
`SERIAL_7E2` +
`SERIAL_8E2` +
`SERIAL_5O1` +
`SERIAL_6O1` +
`SERIAL_7O1` +
`SERIAL_8O1` +
`SERIAL_5O2` +
`SERIAL_6O2` +
`SERIAL_7O2` +
`SERIAL_8O2` +

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Códigos de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo inicia a porta serial a 9600 bps.

[source,arduino]
----
void setup() {
    Serial.begin(9600); // inicia a porta serial, configura a taxa de dados para 9600 bps
}

void loop() {
}
----
[%hardbreaks]

*Exemplo para o Arduino Mega:*
O código abaixo inicia todas as portas seriais no Arduino Mega com diferentes taxas de trasnmissão.
[source,arduino]
----
// Exemplo por Jeff Gray (originalmente em Inglês)
// Arduino Mega usando todas suas quatro portas seriais
// (Serial, Serial1, Serial2, Serial3),
// com baud rates diferentes:

void setup() {
  Serial.begin(9600);
  Serial1.begin(38400);
  Serial2.begin(19200);
  Serial3.begin(4800);

  Serial.println("Hello Computer");
  Serial1.println("Hello Serial 1");
  Serial2.println("Hello Serial 2");
  Serial3.println("Hello Serial 3");
}
void loop() {
}
----
[%hardbreaks]


[float]
=== Notes and Warnings
For USB CDC serial ports (e.g. `Serial` on the Leonardo), `Serial.begin()` is irrelevant. You can use any baud rate and configuration for serial communication with these ports. See the list of available serial ports for each board on the link:../../serial[Serial main page].
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
