---
title: Serial.findUntil()
---

= Serial.findUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`Serial.findUntil()` lê dados do buffer serial até uma string especificada de dado tamanho ou um terminador serem encontrados.

A função retorna `true` se a string especificada é encontrada, `false` se ocorre time-out.

A função `Serial.findUntil()` é herdada da classe link:../../stream[Stream].
[%hardbreaks]


[float]
=== Sintaxe
`Serial.findUntil(str, terminal)`


[float]
=== Parâmetros
`str` : a string a ser procurada (*char)
`terminal` : a string terminadora da busca (*char)

[float]
=== Retorna
Se a string foi ou não encontrada no buffer - `boolean`

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas e Advertências

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../stream[stream] +
#LINGUAGEM# link:../../stream/streamfinduntil[stream.findUntil()]

--
// SEE ALSO SECTION ENDS
