---
title: Serial.find()
---

= Serial.find()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Serial.find() lê dados do buffer serial de recebimento até a string especificada ser encontrada. A função retorna `true` se a string denominada é encontrada, `false` se ocorre time-out.

A função `Serial.find()` é herdada da classe link:../../stream[Stream].
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.find(target)` +
`_Serial_.find(target, length)`


[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

`target` : a string para ser procurada no buffer (char[])

`length` : comprimento da string procurada (size_t)

[float]
=== Retorna
`true` ou `false` (tipo booleano)

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver também

[role="language"]
* #LINGUAGEM# link:../../stream[stream] +
* #LINGUAGEM# link:../../stream/streamfind[stream.find()]

--
// SEE ALSO SECTION ENDS
