---
title: if(Serial)
---

= if (Serial)

// OVERVIEW SECTION STARTS
[#overview]
--
[float]
=== Descrição
Indica se a porta serial especificada está pronta.

No Leonardo, `if (Serial)` indica se a conexão serial USB CDC está aberta. Para todas as outras instâncias, incluindo `if (Serial1)` no Leonardo, isso irá sempre retornar `true`.

Essa função foi introduzida na IDE Arduino 1.0.1.
[%hardbreaks]


[float]
=== Sintaxe
_Todas as placas:_

`if (Serial)`

_Específico para o Arduino Leonardo:_

`if (Serial1)`

_Específico para o Arduino Mega:_

`if (Serial1)` +
`if (Serial2)` +
`if (Serial3)`

[float]
=== Parâmetros
Nenhum

[float]
=== Retorna
`boolean` : retorna `true` se a porta serial especificada está disponível. Irá retornar `false` apenas caso verificada a conexão serial USB CDC do Leonardo antes que a mesma esteja pronta.
--

// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo inicializa uma porta serial e espera a mesma conectar.

[source,arduino]
----
void setup() {
  // Inicializa a porta erial
  Serial.begin(9600);
  // Espera ela estar pronta
  while (!Serial) {
    ; // Espera a porta serial conectar. Necessário para USB nativa
  }
}

void loop() {
 //porcede normalmente
}
----

--
// HOW TO USE SECTION ENDS
