---
title: if(Serial)
---

= if (Serial)

// OVERVIEW SECTION STARTS
[#overview]
--
[float]
=== Descrição
Indica se a porta serial especificada está pronta.

Nas placas com USB nativa, `if (Serial)`, ou `if(SerialUSB)` no Due, indica se a conexão serial USB CDC está aberta. Para todas as outras placas, e portas seriais não USB CDC, isso irá sempre retornar `true`.

Essa função foi introduzida na IDE Arduino 1.0.1.
[%hardbreaks]


[float]
=== Sintaxe
`if (Serial)`

[float]
=== Parâmetros
Nenhum

[float]
=== Retorna
`bool` : retorna `true` se a porta serial especificada está disponível. Irá retornar `false` apenas caso verificada a conexão serial USB CDC do Leonardo antes que a mesma esteja pronta.
--

// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo inicializa uma porta serial e espera a mesma conectar.

[source,arduino]
----
void setup() {
  // Inicializa a porta erial
  Serial.begin(9600);
  // Espera ela estar pronta
  while (!Serial) {
    ; // Espera a porta serial conectar. Necessário para USB nativa
  }
}

void loop() {
  //porcede normalmente
}
----

--
// HOW TO USE SECTION ENDS
