---
title: Serial.parseFloat()
---

= Serial.parseFloat()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`Serial.parseFloat()` retorna o primeiro número válido de ponto flutuante do buffer serial. Caracteres que não são dígitos (ou o sinal de menos) são pulados. `parseFloat()` é terminada pelo primeiro caractere que não é um número de ponto flutuante. A função retorna se acabar o tempo limite (veja link:../settimeout[Serial.setTimeout()]).

A função `Serial.parseFloat()` é herdada da classe link:../../stream[Stream].
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.parseFloat()`

[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

[float]
=== Retorna
O primeiro número válido `float` no buffer de recebimento. (float)

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver também

[role="language"]
#LINGUAGEM# link:../../stream[stream()] +
#LINGUAGEM# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
