---
title: Serial.parseInt()
---

= parseInt()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Procura o próximo inteiro válido no buffer de recebimento serial. A função `stream.parseInt()` é herdada da classe link:../../stream[Stream].

Em particular:

* Caracteres iniciais que não são dígitos ou um sinal de menos, são ignorados; +
* O Parsing termina quando caractetes não foram lidos em um time-out configurável, ou um valor não-digito é lido; +
* Se nenhum dígito válido foi lido quando ocorre o time-out (ver Serial.setTimeout()), 0 é retornado;
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.parseInt()`
`_Serial_.parseInt(char skipChar)`

[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

`skipChar`: usado para ignorar o caractere indicado na busca. Usado, por exemplo, para ignorar o ponto em "2.000.000".

[float]
=== Retorna
O próximo inteiro válido - `long`.

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../begin[begin()] +
#LINGUAGEM# link:../end[end()] +
#LINGUAGEM# link:../available[available()] +
#LINGUAGEM# link:../read[read()] +
#LINGUAGEM# link:../peek[peek()] +
#LINGUAGEM# link:../flush[flush()] +
#LINGUAGEM# link:../print[print()] +
#LINGUAGEM# link:../println[println()] +
#LINGUAGEM# link:../write[write()] +
#LINGUAGEM# link:../serialevent[SerialEvent()] +
#LINGUAGEM# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
