---
title: Serial.peek()
---

= peek()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Retorna o próximo byte (caractere) de dados seriais recebidos sem o remover do buffer serial interno. Isto é, successivas chamadas de  `peek()` irão retornar o mesmo caractere, assim como irá a próxima chamada de `read()`. A função `peek()` é herdada da classe link:../../stream[Stream].
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.peek()`

[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

[float]
=== Retorna
O primeiro byte dos dados seriais recebidos disponível (ou -1 se não há dados disponíveis) - `int`

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../begin[begin()] +
#LINGUAGEM# link:../end[end()] +
#LINGUAGEM# link:../available[available()] +
#LINGUAGEM# link:../read[read()] +
#LINGUAGEM# link:../peek[peek()] +
#LINGUAGEM# link:../flush[flush()] +
#LINGUAGEM# link:../print[print()] +
#LINGUAGEM# link:../println[println()] +
#LINGUAGEM# link:../write[write()] +
#LINGUAGEM# link:../serialevent[SerialEvent()] +
#LINGUAGEM# link:../../stream/streampeek[Stream.peek()]

--
// SEE ALSO SECTION ENDS
