---
title: Serial.println()
---

= println()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Imprime dados na porta serial como texto ASCII seguido pelo caratere de retorno de carruagem (ASCII 13, ou '\r') e um cactere de nova linha (ASCII 10, ou '\n'). Essa função assume as mesmas formas que link:../print[Serial.print()].
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.println(val)` +
`_Serial_.println(val, formato)`

[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

`val`: o valor a ser impresso - qualquer tipo de dados

`formato`: especifica a base do numeral (para tipos de dados int) ou número de casas decimais (para tipos de dados float)

[float]
=== Retorna
`size_t`: `println()` retorna o número de bytes escritos, porém a leitura desse número é opcional
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo faz a leitura de um valor analógico a cada 10 ms e imprime esse valor na porta serial em vários formatos.
[source,arduino]
----
/*
 Lê um valor analógico no pino de entrada analógica 0, imprime esse dado na porta serial.
 criado em 24 de Março de 2006 por Tom Igoe
 Tradução em 29 de Novembro de 2017
 */

int analogValue = 0;    // variável para guardar a leitura analógica

void setup() {
  // abre a porta serial a 9600 bps:
  Serial.begin(9600);
}

void loop() {
  // Lê o valor analógico no pino 0:
  analogValue = analogRead(0);

  // Imprime a leitura em vários formatos:
  Serial.println(analogValue);       // imprime como decimal (padrão) codificado em ASCII
  Serial.println(analogValue, DEC);  // imprime como decimal codificado em ASCII
  Serial.println(analogValue, HEX);  // imprime como hexadecimal codificado em ASCII
  Serial.println(analogValue, OCT);  // imprime como octal codificado em ASCII
  Serial.println(analogValue, BIN);  // imprime como binário codificado em ASCII

  // espera 10 milissegundos antes da próxima leitura:
  delay(10);
}
----
[%hardbreaks]

[float]
=== Notas e Advertências
Desde a versão 1.0 da IDE do Arduino, a trasmissão serial é assíncrona.; Para mais informações sobre a assincronicidade de `Serial.print()`, veja a seção Notas e Advertências da página de referência da link:../write#howtouse[função Serial.write()].

--
// HOW TO USE SECTION ENDS
