---
title: Serial.readBytesUntil()
---

= Serial.readBytesUntil()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Serial.readBytesUntil() lê caracteres da porta serial e os move para um buffer. A função termina se o caractere terminador foi encontrado, se a quantidade de bytes determinada foi lida, ou se ocorre time-out (ver link:../settimeout[Serial.setTimeout()]). A função retorna os caracteres até o último antes do caractere terminador especificado. O caractere terminador não é movido para o buffer.

`Serial.readBytesUntil()` retorna o número de caracteres colocados no buffer. Um valor 0 indica que dados não foram encontrados.

`Serial.readBytesUntil()` é herdada da classe link:../../stream[Stream].
[%hardbreaks]


[float]
=== Sintaxe
`Serial.readBytesUntil(character, buffer, length)`


[float]
=== Parâmetros
`character` : o charactere que encerra a busca (`char`)

`buffer`: o buffer para se armazenar os bytes (`char[]` ou `byte[]`)

`length` : o número de bytes a serem lidos (`int`)

[float]
=== Retorna
o número de bytes colocados no buffer (`size_t`)

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../stream[Stream] +
#LINGUAGEM# link:../../stream/streamreadbytesuntil[Stream.readBytesUntil()]

--
// SEE ALSO SECTION ENDS
