---
title: Serial.readStringUntil()
---

= readStringUntil()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`Serial.readStringUntil()` ê caracteres do buffer serial e os move para uma String. A função termina se o caractere terminador é encontrado, ou se  ocorre time-out (ver link:../settimeout[setTimeout()]).

A função `Serial.readStringUntil()` é herdada da classe link:../../stream[Stream].

[%hardbreaks]

[float]
=== Sintaxe
`_Serial_.readStringUntil(terminador)`


[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

`terminador` : o caractere que encerra a busca (`char`)

[float]
=== Retorna
A String completa lida do buffer serial, até o caractere terminador ser encontrado.

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../serial[Serial] +
#LINGUAGEM# link:../begin[begin()] +
#LINGUAGEM# link:../end[end()] +
#LINGUAGEM# link:../available[available()] +
#LINGUAGEM# link:../read[read()] +
#LINGUAGEM# link:../peek[peek()] +
#LINGUAGEM# link:../flush[flush()] +
#LINGUAGEM# link:../print[print()] +
#LINGUAGEM# link:../println[println()] +
#LINGUAGEM# link:../write[write()] +
#LINGUAGEM# link:../serialevent[SerialEvent()] +
#LINGUAGEM# link:../../stream/streamparsefloat[stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
