---
title: Serial.readBytes()
---

= Serial.readBytes()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`Serial.readBytes()` lê caracteres da porta serial e os move para um buffer. A função termina se a quantidade de bytes determinada foi lida, ou se ocorre time-out (ver link:../settimeout[Serial.setTimeout()]).

`Serial.readBytes()` retorna o número de caracteres colocados no buffer. Um valor 0 implica que dados não foram encontrados.

`Serial.readBytes()` é herdada da classe link:../../stream[Stream].
[%hardbreaks]


[float]
=== Sintaxe
`Serial.readBytes(buffer, length)`


[float]
=== Parâmetros
`buffer`: o buffer para se armazenar os bytes (`char[]` ou `byte[]`)

`length` : o número de bytes a serem lidos (`int`)

[float]
=== Retorna
o número de bytes colocados no buffer (`size_t`)

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../stream[stream] +
#LINGUAGEM# link:../../stream/streamreadbytes[stream.readBytes()]

--
// SEE ALSO SECTION ENDS
