---
title: serialEvent()
---

= serialEvent()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Chamada quando dados estão disponíveis no buffer serial. Use `Serial.read()` para ler esses dados.

[%hardbreaks]


[float]
=== Sintaxe

[source,arduino]
----
void serialEvent() {
  //código
}
----
Para placas com portas seriais adicionais (veja a lista de portas seriais disponíveis para cada placa no link:../../serial[Serial - Página principal]):
[source,arduino]
----
void serialEvent1() {
  //código
}

void serialEvent2() {
  //código
}

void serialEvent3() {
  //código
}
----

[float]
=== Parâmetros
`código`: quaisquer linhas de código válidas

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas e Advertências
`serialEvent()` não funciona no Leonardo, Micro ou Yún.

`serialEvent()` e `serialEvent1()` não funcionam nas placas Arduino SAMD.

`serialEvent()`, `serialEvent1()`, `serialEvent2()`, e `serialEvent3()` não funcionam no Arduino Due.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="example"]
#EXEMPLO# http://arduino.cc/en/Tutorial/SerialEvent[Serial Event Tutorial (Em Inglês)^] +

[role="language"]
#LINGUAGEM# link:../begin[begin()] +
#LINGUAGEM# link:../end[end()] +
#LINGUAGEM# link:../available[available()] +
#LINGUAGEM# link:../read[read()] +
#LINGUAGEM# link:../peek[peek()] +
#LINGUAGEM# link:../flush[flush()] +
#LINGUAGEM# link:../print[print()] +
#LINGUAGEM# link:../println[println()] +
#LINGUAGEM# link:../write[write()]

--
// SEE ALSO SECTION ENDS
