---
title: Serial.setTimeout()
---

= Serial.setTimeout()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
`Serial.setTimeout()` configura o número máximo de milissegundos a se esperar por dados seriais. O valor padrão é de 1000 milisegundos.

`Serial.setTimeout()` é herdada da classe link:../../stream[Stream].
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.setTimeout(tempo)`

[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

`tempo` : tempo limite em milisegundos (`long`).

[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas e Advertências
Funções da classe Serial que usam o valor de tempo limite configurado via `_Serial_.setTimeout()`:

* `_Serial_.find()`
* `_Serial_.findUntil()`
* `_Serial_.parseInt()`
* `_Serial_.parseFloat()`
* `_Serial_.readBytes()`
* `_Serial_.readBytesUntil()`
* `_Serial_.readString()`
* `_Serial_.readStringUntil()`

[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
#LINGUAGEM# link:../../stream[stream] +
#LINGUAGEM# link:../../stream/streamsettimeout[stream.setTimeout()]

--
// SEE ALSO SECTION ENDS
