---
title: Serial.write()
---

= write()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Escreve dados binários na porta serial. Esses dados são enviados como um byte ou séries de bytes; para enviar os caracteres representando os dígitos de um número, use em vez disso a função link:../print[print()].
[%hardbreaks]


[float]
=== Sintaxe
`_Serial_.write(val)` +
`_Serial_.write(str)` +
`_Serial_.write(buf, len)`


[float]
=== Parâmetros
`_Serial_`: objeto porta serial. Veja a lista de portas seriais disponíveis em cada placa no link:../../serial[Serial - Página principal]

`val`: o valor a ser enviado como um único byte.

`str`: uma string a ser enviada como uma série de bytes.

`buf`: um vetor a ser enviado como uma série de bytes.

[float]
=== Retorna

O número de bytes escritos na porta serial - `size_t`

`write()` irá retornar o número de bytes escritos, apesar de ler esse valor ser opcional 

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O código abaixo usa a função Serial.write() para escrever um valor e uma string na porta serial. 

[source,arduino]
----
void setup() {
  Serial.begin(9600);
}

void loop() {
  Serial.write(45); // envia um byte com valor 45 (0b101101)

  int bytesSent = Serial.write(“hello”);  //envia a string “hello” e retorna o tamanho da string.
}
----

--
// HOW TO USE SECTION ENDS
