---
title: pulseIn()
categories: [ "Functions" ]
subCategories: [ "Entradas e Saídas Avançadas" ]
---

= pulseIn()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Captura a duração de um pulso em um pino (que pode ser `HIGH` ou `LOW`). Por exemplo, se o valor `HIGH` é passado para a função, a função `pulseIn()` espera o pino ir para do estado 'LOW' para `HIGH`, começa a temporizar, então espera o pino ir para o estado `LOW` e para de temporizar. Retorna o tamanho do pulso em microssegundos ou desiste e retorna 0 se não receber nenhum pulso dentro de um tempo máximo de espera especificado.

A temporização dessa função foi determinada empiricamente e irá provavelmente mostrar erros em pulsos mais longos. funciona em pulsos de 10 microssegundos a 3 minutos de duração.
[%hardbreaks]


[float]
=== Sintaxe
`pulseIn(pino, valor)`

`pulseIn(pino, valor, tempo_de_espera)`

[float]
=== Parâmetros
`pino`: o número do pino no Arduino no qual se quer capturar a duração de um pulso. (int)

`valor`: tipo de pulso a ser lido: pode ser link:../../../variables/constants/constants/[HIGH] ou link:../../../variables/constants/constants/[LOW]. (int)

`tempo_de_espera` (opcional): o número de microssegundos a se esperar pelo começo do pulso; o padrão é um segundo. (unsigned long)
[float]
=== Retorna
A duração do pulso (em microssegundos) ou 0 se nenhum pulso começar antes de se esgotar o tempo de espera (unsigned long).

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de Exemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
O exemplo abaixo imprime a duração de um pulso no pino 7.

[source,arduino]
----
int pino = 7;           //pino para a entrada do pulso
unsigned long duracao; //variável para guardar a duração do pulso

void setup()
{
  Serial.begin(9600);
  pinMode(pino, INPUT);
}

void loop()
{
  duracao = pulseIn(pino, HIGH);
  Serial.println(duracao);
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

--
// SEE ALSO SECTION ENDS
