---
title: tone()
categories: [ "Functions" ]
subCategories: [ "Entradas e Saídas Avançadas" ]
---





= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrição
Gera uma onda quadrada na frequência especificada (e duty cycle 50%) em um pino. A duração pode ser especificada, do contrário a onda continua até uma chamada de link:../noTone[noTone()]. O pino pode ser conectado a um buzzer piezo ou outro speaker para tocar tons.

Apenas um tom pode ser gerado de cada vez. Se um tom já está tocando em um pino diferente, a chamada de tone() não terá efeito. Se o tom está tocando no mesmo pino, a chamada irá mudar sua frequência para a nova especificada.

Uso da função `tone()` irá interferir com saída PWM nos pinos 3 e 11 (em placas diferentes do Mega).

Não é possível gerar tons de freqeuência mais baixa que 31Hz. Para detalhes técnicos, veja https://github.com/bhagman/Tone#ugly-details[as notas de Brett Hagman's(Em Inglês)].
[%hardbreaks]


[float]
=== Sintaxe
`tone(pino, frequência)`

`tone(pino, frequência, duração)`
[%hardbreaks]

[float]
=== Parâmetros
`pino`: o pin no qual gerar o tom

`frequência`: a frequência do tom em Hertz - `unsigned int`

`duração`: a duração do tom em milissegundos (opcional) - `unsigned long`
[%hardbreaks]

[float]
=== Retorna
Nada.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas e Advertências
Se você quiser tocar tons diferentes em múltiplos pinos, você precisa chamar `noTone()` em um pino antes de chamar `tone()` no próximo pino.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver Também

[role="language"]
* #LINGUAGEM# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]
* #EXEMPLO# http://arduino.cc/en/Tutorial/Tone[Tone^]
* #EXEMPLO# http://arduino.cc/en/Tutorial/tonePitchFollower[Pitch follower^]
* #EXEMPLO# http://arduino.cc/en/Tutorial/Tone3[Simple Keyboard^]
* #EXEMPLO# http://arduino.cc/en/Tutorial/Tone4[multiple tones^]
* #EXEMPLO# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS
